### PR TITLE
assumptions: fix AttributeError regression in refine_sin_cos

### LINKED ISSUE #27888: Refine is not able to make many simplifications
It's unlikely that I will review future PRs related to this issue atm. Do not ping people or email people to review your PRs.

---

I've added the "good first issue" and "Easy to fix" labels not because I think fixing parts of this issue is easy - it's not. Rather, it's because: 

1) It likely shouldn't require any super advanced math.
2) I think it's straightforward to understand what the goal is here (enable SymPy's `refine` function to simplify more cases). 
3) This is really many issues bundled together - so there's a lot of room for many different people to contribute parts of this overall issue. I don't expect the work to dry up any time soon. 
4) I'm happy to help guide new contributors through the process. **However, please do not ask for help without first opening a pull request with some sort of approach you're put effort into.** This offer lasts at least through spring 2026 - who knows if I will have time for this beyond then!

To get started:

-1. Anything related to inequalities is not an easy or good choice (e.g. piecewise is not a good choice). The fix for such issues has to do with `ask` and not refine.
0. Look through some example pull requests listed below.
1. Look through [refine.py](https://github.com/sympy/sympy/blob/master/sympy/assumptions/refine.py).
2. Identify a type of function that is not handled yet (and double check that it's actually not handled). Keep in mind that for some functions, the simplification logic might be very difficult and not suited for new contributors. This entire issue could potentially be a small / medium GSoC project. 
3. Check to see that no one else is currently trying to implement the same thing. If someone had tried to implement it before but never finished their work, feel free to revive their pull request. 
4. If you haven't already, read through [the guide for new contributors](https://docs.sympy.org/latest/contributing/new-contributors-guide/index.html).
5. Open a new pull request implementing the new refine handler for your function. 

#### Successful pull requests

- https://github.com/sympy/sympy/pull/28873
  -  https://github.com/sympy/sympy/pull/29276
- https://github.com/sympy/sympy/pull/29174
- (very simple!) https://github.com/sympy/sympy/pull/29325 

####  Unsuccessful pull requests (try not to repeat these mistakes!)

- https://github.com/sympy/sympy/pull/29364 

#### Link to all open refine related pull requests
- https://github.com/sympy/sympy/pulls?q=is%3Apr+is%3Aopen+label%3Aassumptions.refine+

#### Link to all closed refine related pull requests (you might be able to revive some of these)
- https://github.com/sympy/sympy/pulls?q=is%3Apr+label%3Aassumptions.refine+is%3Aclosed

 **_PLEASE DO NOT DELETE PR TEMPLATE WHEN YOU OPEN A NEW PR. YOUR PR WILL BE CLOSED IF YOU DO._**

### PR DESCRIPTION
**Pull request by CharlieLam802**
#### References to other Issues or PRs
Fixes regression introduced in #29276, reported by @bilichboris in #27888

#### Brief description of what is fixed or changed
A regression introduced in #29276 caused an AttributeError: 'One' object has no attribute 'base'. The issue was that (-1)**(k/2) can evaluate to 1 (a One object) before reaching refine_Pow, which expects a Pow object and tries to access .base on it. Fixed by checking isinstance(pow_expr, Pow) before calling refine_Pow, so plain numbers like 1 or -1 are returned directly without going through refine_Pow. All tests pass.

#### Release Notes

NO ENTRY

### CODE REVIEW

File: sympy/assumptions/refine.py [hunk 1]
```diff
@@ -476,8 +476,10 @@ def refine_sin_cos(expr, assumptions):
...
         pow_expr = (-1)**(k / 2)
-        refined_pow = refine_Pow(pow_expr, assumptions)
-        return (pow_expr if refined_pow is None else refined_pow) * cos(rem)
+        if isinstance(pow_expr, Pow):
+           refined_pow = refine_Pow(pow_expr, assumptions)
+           pow_expr = refined_pow if refined_pow is not None else pow_expr
+        return pow_expr * cos(rem)
     else:
         pow_expr = (-1)**((k + 1) / 2)
         refined_pow = refine_Pow(pow_expr, assumptions)
```
Comment (SujalKumar06) [inline sympy/assumptions/refine.py]: There should be a check here as well.

**Comment by SujalKumar06** [comment]
Hey @TiloRC @CharlieLam802 ,

Can you explain why was this change introduced in #29276, when I was writing the function, even I had a doubt if it should call `refine_Pow` but refine calls it recursively anyways. Like I feel this change might have been redundant but feel free to correct me. 

Refining things like `(-1)**k` shouldn't be handled by `refine_sin_cos`

**Comment by SujalKumar06** [comment]
Also I think it is better if we have more tests of such sort as pointed in https://github.com/sympy/sympy/issues/27888#issuecomment-4080374593, this regression should have not been added if the tests were a little more broad.

**Comment by CharlieLam802** [comment]
Hey @SujalKumar06, you're right. The refine_Pow call is redundant. Since refine calls return refine(new_expr, assumptions) on the result, it will automatically dispatch to refine_Pow on any (-1)**k sub-expressions. I'll remove it.

**Comment by TiloRC** [comment]
> refine_Pow but refine calls it recursively anyways

`refine_sin_cos` is not just a handler function. Someone might want to use it instead of calling `refine` because they want to perform more targeted simplifications instead of doing all possible simplifications. The simplify function recommends that you use it in this way in some situations: https://docs.sympy.org/latest/modules/simplify/simplify.html. 

So if `refine_sin_cos` was called instead of `refine` it would be good to return as simple expression as possible.

**Comment by SujalKumar06** [comment]
> So if refine_sin_cos was called instead of refine it would be good to return as simple expression as possible.

Cool, seems reasonable, I think the last commit can be dropped. Its better to have `refine_Pow` inside it.

**Comment by CharlieLam802** [comment]
Thanks @TiloRC and @SujalKumar06 for the clarification! I've reverted the removal and restored refine_Pow inside refine_sin_cos. 

Regarding more tests, I agree with your point, that would have caught the regression earlier.

**Comment by TiloRC** [comment]
See https://docs.sympy.org/latest/contributing/new-contributors-guide/workflow-process.html

You need to add tests.
