### PR TITLE
Minor fixes for ConditionSet and Piecewise

### PR DESCRIPTION
**Pull request by Maelstrom6**
#### References to other Issues or PRs

Partial fixes for some of #20101

#### Brief description of what is fixed or changed

Fixes some minor functionality for `ConditionSet` and `Piecewise`. 
Most of the new tests added were not possible in the master branch.

#### Other comments

1. `as_expr_set_pairs` in `Piecewise` is supposed to return a list of tuples where each item in the list is a tuple of `(<value of piecewise>, <set for which it is valid>)` for a given domain. It sometimes returned tuples containing `EmptySet`. This caused problems in `solveset` which assumed all sets were non-empty. `solveset` is the only thing in SymPy that uses `as_expr_set_pairs`.

2. `ConditionSet` is now able to denest/flatten expressions such as `ConditionSet(x, Contains(x, A))`. This simply becomes `A`. Further work is needed if we have expressions of the form `ConditionSet(x, And(Contains(x, A), ...))` or other similar forms.

3. Checking if elements were in the set were also not possible with matrix equalities. This update adds a `doit()` to turn `Eq` into a boolean if possible.

#### Release Notes

* sets
  * Added basic denesting functionaility for sets of the form `ConditionSet(x, Contains(x, ...))`.
  * `ConditionSet.contains(x)` now returns `False` if `x` is not in the base set (even if its substitution into the condition will cause an error).
* calculus
  * Using `maximum` with a piecewise expression over a domain no longer fails due to a bug fix in `Piecewise.as_expr_set_pairs`.

### CODE REVIEW

File: sympy/sets/conditionset.py [hunk 1]
```diff
@@ -190,11 +195,33 @@ def ok_sig(a, b):
...
+
+        # try doing base_cond first and return
+        # False immediately if it is False
         try:
-            return And(
-                Contains(other, self.base_set),
-                Lambda((self.sym,), self.condition)(other))
+            base_cond = Contains(other, self.base_set)
+            base_error = False
         except TypeError:
```
Comment (oscarbenjamin) [inline sympy/sets/conditionset.py:207]: Where does the `TypeError` come from?

(I realise that you didn't add that but I'm just wondering since I look at this)

Comment (Maelstrom6) [reply sympy/sets/conditionset.py:207]: The only time I experienced the `TypeError` was when it creates the lambda function and then evaluates it. If the lambda function expects something similar to symbols, and you pass in an (unevaluated) function (like `f` in the tests), it would raise.

I couldn't raise a `TypeError` with `base_cond` but I'd rather be safe than accidentally break a user's code.

Comment (oscarbenjamin) [reply sympy/sets/conditionset.py:207]: Fair enough. I just asked because I would like to remove most cases of `except TypeError` from the codebase as it can easily hide bugs.

Comment (oscarbenjamin) [reply sympy/sets/conditionset.py:207]: Actually I think it's fine to have an exception when using an unevaluated function `f` since `f` is not an instance of `Basic`.

File: sympy/sets/conditionset.py [hunk 2]
```diff
@@ -190,11 +195,33 @@ def ok_sig(a, b):
...
+            return False
+
+        try:
+            lambda_cond = (Lambda((self.sym,), self.condition)(other)).doit()
+            lambda_error = False
+        except TypeError:
+            lambda_cond = None
+            lambda_error = True
+        if (not lambda_error) and (lambda_cond is S.false):
+            return False
```
Comment (oscarbenjamin) [inline sympy/sets/conditionset.py:220]: I find this code quite convoluted and I think I prefer the way it was written before. This would be clearer I think without the `lambda_cond` and `lambda_error` variables.

I don't like catching `TypeError` as it makes me think that either we should be checking the types before the operation or the operation shouldn't raise a `TypeError`. Catching the `TypeError` seems like working around either a bug or a poor definition of what the scope of the function is.

I'm also not sure that we should call doit here as that can lead to arbitrarily expensive evaluation.

File: sympy/sets/conditionset.py (hunk 1 above)
Comment (Maelstrom6) [reply sympy/sets/conditionset.py:207]: I would prefer it as it is because, functions are mathematical objects in their own right. So we could have functions being elements of sets and also not being elements of sets. 

I think other parts of the code base also assume it will not throw in cases such as this. That's kind of how I came across it. This method would sometimes return an unevaluated expression while working in `solveset`. Thus a `TypeError` must have been raised. But `And(False, <TypeError>)` should be `False` and that's why I decided to change it.

I can remove the try-catch for `base_cond` because I couldn't find out how it would raise. But I didn't want to cause problems with users' code where not having it might cause problems.

File: sympy/sets/conditionset.py (hunk 2 above)
Comment (Maelstrom6) [reply sympy/sets/conditionset.py:220]: > I find this code quite convoluted and I think I prefer the way it was written before. This would be clearer I think without the lambda_cond and lambda_error variables.

The reason why it was done is to allow one or more of [these](https://github.com/sympy/sympy/issues/20101#issuecomment-694959855) problems to be fixed. (I can't remember which ones).

> I don't like catching TypeError as it makes me think that either we should be checking the types before the operation or the operation shouldn't raise a TypeError.

Reason for doing so is [here](https://github.com/sympy/sympy/pull/20121#discussion_r491949054).

> I'm also not sure that we should call doit here as that can lead to arbitrarily expensive evaluation.

This was needed so that we don't get errors for the following added tests:
https://github.com/sympy/sympy/pull/20121/files#diff-91900d1e8fe044ea6c7601b777d5f895R38-R44
This matrix functionality will be used in the stats module soon. Current master should not raise with these new tests if we replace `... in ...` with `Contains(..., ...)`. But I think `in` is more user-friendly than `Contains`.

Comment (oscarbenjamin) [reply sympy/sets/conditionset.py:220]: > But I think `in` is more user-friendly than `Contains`.

We shouldn't use `in` in the codebase because there is no general way to stop it from raising. Python requires it to give True or False (unlike e.g. `<`) and many queries are indeterminate e.g.:
```julia
In [1]: x = Symbol('x')                                                                                                                        

In [2]: x in Reals                                                                                                                             
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-2-c53dfd933383> in <module>
----> 1 x in Reals

~/current/sympy/sympy/sympy/sets/sets.py in __contains__(self, other)
    673             # x in y must evaluate to T or F; to entertain a None
    674             # result with Set use y.contains(x)
--> 675             raise TypeError('did not evaluate to a bool: %r' % c)
    676         return b
    677 

TypeError: did not evaluate to a bool: (-oo < x) & (x < oo)
```

> the `doit()` call should not be expensive since 99.99% of the time, it's calling doit on `S.true` or `S.false`.

Well then it's not needed 99.99% of the time :)

We should only use `doit` in library code if we're sure we know what sympy classes it is going to act on. If we add a `doit` in `_contains` then there is no way for a user to prevent it in the situations where it is slow.

Comment (Maelstrom6) [reply sympy/sets/conditionset.py:220]: > Well then it's not needed 99.99% of the time :)

:smirk: That's a dangerous argument. Division by 0 checks aren't needed often either...

I agree with your other arguments though and I'll remove the `doit()`.

**Comment by oscarbenjamin** [comment]
What about this:
```python
        # try doing base_cond first and return
        # False immediately if it is False
        base_cond = Contains(other, self.base_set)
        if base_cond is S.false:
            return False

        # Subsitute other into condition. This could raise e.g. for
        # ConditionSet(x, 1/x >= 0, Reals).contains(0)
        lamda = Lambda((self.sym,), self.condition)
        try:
            lambda_cond = lamda(other)
        except TypeError:
            return Contains(other, self, evaluate=False)
        else:
            return And(base_cond, lambda_cond)
```
This is a diff compared to this PR:
```diff
diff --git a/sympy/sets/conditionset.py b/sympy/sets/conditionset.py
index f01fe33683..3f7050db24 100644
--- a/sympy/sets/conditionset.py
+++ b/sympy/sets/conditionset.py
@@ -201,28 +201,19 @@ def ok_sig(a, b):
 
         # try doing base_cond first and return
         # False immediately if it is False
-        try:
-            base_cond = Contains(other, self.base_set)
-            base_error = False
-        except TypeError:
-            base_cond = None
-            base_error = True
-        if (not base_error) and (base_cond is S.false):
+        base_cond = Contains(other, self.base_set)
+        if base_cond is S.false:
             return False
 
+        # Subsitute other into condition. This could raise e.g. for
+        # ConditionSet(x, 1/x >= 0, Reals).contains(0)
+        lamda = Lambda((self.sym,), self.condition)
         try:
-            lambda_cond = (Lambda((self.sym,), self.condition)(other)).doit()
-            lambda_error = False
+            lambda_cond = lamda(other)
         except TypeError:
-            lambda_cond = None
-            lambda_error = True
-        if (not lambda_error) and (lambda_cond is S.false):
-            return False
-
-        if (not base_error) and (not lambda_error):
-            return And(base_cond, lambda_cond)
-        else:
             return Contains(other, self, evaluate=False)
+        else:
+            return And(base_cond, lambda_cond)
 
     def as_relational(self, other):
         f = Lambda(self.sym, self.condition)
diff --git a/sympy/sets/sets.py b/sympy/sets/sets.py
index 65e42a9480..d0241b1f20 100644
--- a/sympy/sets/sets.py
+++ b/sympy/sets/sets.py
@@ -322,6 +322,15 @@ def contains(self, other):
         False
         """
         other = sympify(other, strict=True)
+
+        # Any element of a Set must be of type Basic. Normally sympify always
+        # returns Basic but a Function like sin or cos will sympify to itself
+        # even though it is not Basic e.g.
+        #    >>> sin in FiniteSet(1, 2)
+        # Allowing non-Basic instances through can lead to bugs down the line.
+        if not isinstance(other, Basic):
+            return S.false
+
         c = self._contains(other)
         if isinstance(c, Contains):
             return c
diff --git a/sympy/sets/tests/test_conditionset.py b/sympy/sets/tests/test_conditionset.py
index 8bc6d54b4f..08a18a4f71 100644
--- a/sympy/sets/tests/test_conditionset.py
+++ b/sympy/sets/tests/test_conditionset.py
@@ -37,10 +37,10 @@ def test_CondSet():
 
     X = MatrixSymbol('X', 2, 2)
     matrix_set = ConditionSet(X, Eq(X*Matrix([[1, 1], [1, 1]]), X))
-    X = Matrix([[0, 0], [0, 0]])
-    assert X in matrix_set
-    X = Matrix([[1, 2], [3, 4]])
-    assert X not in matrix_set
+    Y = Matrix([[0, 0], [0, 0]])
+    assert matrix_set.contains(Y).doit() is S.true
+    Z = Matrix([[1, 2], [3, 4]])
+    assert matrix_set.contains(Z).doit() is S.false
 
     assert isinstance(ConditionSet(x, x < 1, {x, y}).base_set,
         FiniteSet)
```

**Comment by Maelstrom6** [comment]
Thanks, that method looks a lot cleaner. 

It makes me a little heartbroken that the following was never possible in the first place:

```python
from sympy import *

f = Function('f')
A = ConditionSet(f, Eq(f(0), 0))
print(sin in A)

x = symbols('x')
B = ConditionSet(2*x, Contains(x, S.Integers))
print(4 in B)
# alternative: ConditionSet(x, Contains(x/2, S.Integers))
```

**Comment by oscarbenjamin** [comment]
> It makes me a little heartbroken that the following was never possible in the first place:

The problem is that functions are not `Basic` instances but are actually Python classes. This is also True of undefined functions like `Function('f')` whose type `UndefinedFunction` is actually a metaclass:
```julia
In [4]: isinstance(sin(x), sin)                                                                                                                
Out[4]: True

In [5]: isinstance(f(x), f)                                                                                                                    
Out[5]: True
```
There have been (and are still) attempts to change this e.g. #19953 but it isn't trivial. The basic fact that `sin(x)` is an instance of `sin` is baked into the codebase in various ways.

**Comment by Maelstrom6** [comment]
It has never failed on this PR before. [TypeError: `__new__()` got an unexpected keyword argument '_sympify'](https://travis-ci.org/github/sympy/sympy/jobs/729076731)

[The previous](https://travis-ci.org/github/sympy/sympy/builds/729020424) build failed because of a timeout error.

Very strange.

The only way I know how to restart jobs on sympy's side is to close and open the PR. Is there a better way to do this?

**Comment by oscarbenjamin** [comment]
If I sign in to Travis then I can restart individual jobs by clicking the restart button at the rhs.

I think this is a genuine failure though due to #19463

**Comment by oscarbenjamin** [comment]
Yes, the master build itself has failed:
https://travis-ci.org/github/sympy/sympy/builds/729076156

This PR failed because the tests are run after merging with master.

**Comment by Maelstrom6** [comment]
> If I sign in to Travis then I can restart individual jobs by clicking the restart button at the rhs.

I assume you mean that you can sign in with the sympy account. I can only restart my personal jobs such as [this one](https://travis-ci.org/github/Maelstrom6/sympy) but I can't restart sympy's jobs for my PR such as [this one](https://travis-ci.org/github/sympy/sympy/builds/729076727).

> I think this is a genuine failure though due to #19463

All right. I'll relax until it's sorted.

**Comment by oscarbenjamin** [comment]
I've closed and reopened to restart the tests. It is necessary to do that in cases like this because restarting the job on Travis does not remerge with the new master which is now fixed from https://github.com/sympy/sympy/pull/20125

File: sympy/sets/sets.py [hunk 3]
```diff
@@ -322,6 +322,15 @@ def contains(self, other):
...
         """
         other = sympify(other, strict=True)
+
+        # Any element of a Set must be of type Basic. Normally sympify always
+        # returns Basic but a Function like sin or cos will sympify to itself
+        # even though it is not Basic e.g.
+        # >>> sin in FiniteSet(1, 2)
+        # Allowing non-Basic instances through can lead to bugs down the line.
+        if not isinstance(other, Basic):
+            return S.false
```
Comment (oscarbenjamin) [inline sympy/sets/sets.py:332]: This isn't needed any more after #20128

File: sympy/sets/conditionset.py [hunk 4]
```diff
@@ -161,6 +161,11 @@ def sig(s):
                 condition = And(condition.xreplace(reps), c)
                 base_set = b
 
+        # flatten ConditionSet(Contains(ConditionSet())) expressions
+        if isinstance(condition, Contains) and (sym == condition.args[0]):
+                if isinstance(condition.args[1], Set):
+                    return condition.args[1].intersect(base_set)
```
Comment (oscarbenjamin) [inline sympy/sets/conditionset.py:167]: The above two lines can be unindented.

File: sympy/sets/conditionset.py [hunk 5]
```diff
@@ -190,12 +195,22 @@ def ok_sig(a, b):
...
+
+        # try doing base_cond first and return
+        # False immediately if it is False
+        base_cond = Contains(other, self.base_set)
+        if base_cond is S.false:
+            return S.false
+
+        # Substitute other into condition. This could raise e.g. for
+        # ConditionSet(x, 1/x >= 0, Reals).contains(0)
+        lmbda = Lambda((self.sym,), self.condition)
```
Comment (oscarbenjamin) [inline sympy/sets/conditionset.py:207]: We normally use "lamda" rather than "lmbda". Neither looks great though...

Comment (Maelstrom6) [reply sympy/sets/conditionset.py:207]: I've seen some of Google's source use underscores like `lambda_`, `str_`, `int_`. Should I do that instead?

Comment (oscarbenjamin) [reply sympy/sets/conditionset.py]: Maybe that's better. It's not a big problem, I just mention it in passing

Comment (Maelstrom6) [reply sympy/sets/conditionset.py]: I'll leave it as you suggested for now. Maybe in the future, a big PR and refractor all these kinds of problems if it becomes necessary.

**Comment by Maelstrom6** [comment]
#20128 seems to have stopped this from working in the test module:
```python
assert f not in sin_sols_principal
```
This now raises an error instead of returning a Boolean. I might have to change `__contains__` in set.py to surround the `_sympify` with a try-catch. I think even `sin_sols_principal.contains(f)` throws for a similar reason.

Should I remove the test even though it reduces functionality?

**Comment by oscarbenjamin** [comment]
> Should I remove the test even though it reduces functionality?

Was the test there before? I thought it was added in this PR.

**Comment by Maelstrom6** [comment]
Yes this PR adds it. The functionality was available before this PR though.

**Comment by oscarbenjamin** [comment]
The "functionality" was really the result of a bug (#20124).

I'm not sure whether or not this (`f in someset`) should raise. Any object contained by a `Set` should be a `Basic` instance so it can only be `True` if `f` sympifies to a `Basic` instance. In that sense asking if some non-Basic object is a member of a `Set` is a type error. The question is whether `f in someset` should raise an exception or should give `False` though.

It seems it is still possible to create a `Set` with non-Basic because of the use of `sympify` rather than `_sympify`:
```
In [1]: FiniteSet(sin)                                                                                                                         
Out[1]: {sin}

In [2]: sin in FiniteSet(sin)            # gives true in sympy 1.6.2                                                                                                      
---------------------------------------------------------------------------
SympifyError 
```
We get an error trying to use it though:
```
In [3]: FiniteSet(sin) & FiniteSet(1)     # fails with RecursionError in sympy 1.6.2                                                                                                     
---------------------------------------------------------------------------
SympifyError
```

**Comment by Maelstrom6** [comment]
So it seems that it's not really designed to be a feature. I can either remove the test, or change `_sympify` to `sympify` for all the `__contains__` and `_contains` in all set modules.

**Comment by oscarbenjamin** [comment]
> So it seems that it's not really designed to be a feature.

Ideally it would be but first we need to make it so that unapplied functions are `Basic` instances.

**Comment by Maelstrom6** [comment]
I have realized that `Lambda` is a basic type and is also a function. I will try to add back `f in sin_sols_principal` when `f` is a `Lambda` instance. If it doesn't already work, I will try make it work.

**Comment by oscarbenjamin** [comment]
> If it doesn't already work, I will try make it work.

I'm not sure exactly what you mean but we shouldn't fudge this. We don't have a clear system for functions as objects - it would be good to have but we don't have it yet. Attempting to approximate it in the meantime will potentially make it harder to get it right in the end.

**Comment by Maelstrom6** [comment]
> I'm not sure exactly what you mean but we shouldn't fudge this.

My goal is probably just to add a type check so that things like `f in {x in Reals such that ...}` will always return false if `f` is a `Lambda`.

**Comment by Maelstrom6** [comment]
I've rather decided against it. I would have to add type checks for all known sets (for consistency) and I don't think it's worth it. The type check would also have to check for far more than just a `Lambda` instance.

I think I have done everything else for the goal of this PR though.

**Comment by oscarbenjamin** [comment]
I think we can improve checking types of objects if we have something like #20158

**Comment by czgdp1807** [comment]
@oscarbenjamin Is this ready to go?

**Comment by oscarbenjamin** [comment]
The changes look good to me but I think it needs release notes.

**Comment by Maelstrom6** [comment]
Added a release notes for the sets part of the PR. I'm not sure what to say for the other parts of the PR since they fix very complex bugs:
1. The change in `piecewise.py` fixes a `maximize` call which failed because of a `solveset` call.
2. The change in `conditionset.py/ok_sig()` fixes an edge-case failure in `contains`.

**Comment by oscarbenjamin** [comment]
> I'm not sure what to say

Focus on how the change would impact a likely user. Users are unlikely to use Piecewise or ConditionSet directly but if any change there is potentially not backward compatible then it should still be mentioned. Otherwise changes should be referred to high-level functions like `maximize` or `solveset` so something like: 

* calculus
    * Using `maximum` with a piecewise expression no longer fails in some cases after a bug fix in `Piecewise.as_expr_set_pairs`.

**Comment by Maelstrom6** [comment]
It's been a while, but are there any further suggestions?

**Comment by oscarbenjamin** [comment]
Looks good

**Comment by Maelstrom6** [comment]
Just note that with `Piecewise.as_expr_set_pairs`, I made a significant change. `solveset` was the only thing using `as_expr_set_pairs` and I think it manages better with the new change (since it fixes one of the unit tests). 

However, this change might create some unforeseen consequences. I think there won't be a new bug but it's not unlikely. I guess a really in-depth look at `solveset` is the only way to be sure that there is no new bug.

**Comment by Maelstrom6** [comment]
Apologies, I probably should have mentioned that sooner.

Here is where it is used in `solveset`.

https://github.com/sympy/sympy/blob/274b90ec5686a5499e8b20ac9882558dffeb6fb6/sympy/solvers/solveset.py#L1032-L1039

As I say, if `in_set` is the empty set, then it shouldn't even be considered a solution. So, I think what I did improves the overall function. 

However, I feel like I'm missing something. There must have been a reason to consciously include the empty set when others where designing `solveset` and `as_expr_set_pairs`.

**Comment by oscarbenjamin** [comment]
> However, I feel like I'm missing something. There must have been a reason to consciously include the empty set when others where designing `solveset` and `as_expr_set_pairs`.

I wouldn't be so sure about that.

**Comment by Maelstrom6** [comment]
> I wouldn't be so sure about that.

Fingers crossed.
