### ISSUE TITLE
S(srepr()) not identity for MatrixSymbol.as_explicit()

### ISSUE THREAD

**Issue by cbm755** [sympy/sympy#8467]
Consider:

```
In [59]: A = MatrixSymbol('A', 2, 2)

In [60]: print(A)
A

In [61]: srepr(A)
Out[61]: "MatrixSymbol('A', Integer(2), Integer(2))"

In [62]: B = A.as_explicit().as_mutable()

In [63]: pprint(B)
⎡A₀₀  A₀₁⎤
⎢        ⎥
⎣A₁₀  A₁₁⎦

In [89]: B[0] = 6

In [90]: srepr(B)
Out[90]: "MutableDenseMatrix([[Integer(6), MatrixElement(MatrixSymbol('A', Integer(2), Integer(2)), Integer(0), Integer(1))], [MatrixElement(MatrixSymbol('A', Integer(2), Integer(2)), Integer(1), Integer(0)), MatrixElement(MatrixSymbol('A', Integer(2), Integer(2)), Integer(1), Integer(1))]])"
```

I can paste that in and it get an equivalent object (assuming I `from sympy.matrices.expressions.matexpr import MatrixElement`).

But:

```
In [91]: S(srepr(B))
Out[91]: <repr(<sympy.matrices.dense.MutableDenseMatrix at 0x7f54ceb1ae10>) failed: AttributeError: 'MatrixElement' object has no attribute 'parent'>
```

After my failure in #8465, I think I won't try to fix this myself ;-)

**Comment by oscarbenjamin** [comment]
Seems to work fine now:
```julia
In [40]: A = MatrixSymbol('A', 2, 2)                                                                                                           

In [41]: srepr(A)                                                                                                                              
Out[41]: "MatrixSymbol('A', Integer(2), Integer(2))"

In [42]: B = A.as_explicit().as_mutable()                                                                                                      

In [43]: B                                                                                                                                     
Out[43]: 
⎡A₀₀  A₀₁⎤
⎢        ⎥
⎣A₁₀  A₁₁⎦

In [44]: B[0] = 6                                                                                                                              

In [45]: B                                                                                                                                     
Out[45]: 
⎡ 6   A₀₁⎤
⎢        ⎥
⎣A₁₀  A₁₁⎦

In [46]:  srepr(B)                                                                                                                             
Out[46]: "MutableDenseMatrix([[Integer(6), MatrixElement(MatrixSymbol('A', Integer(2), Integer(2)), Integer(0), Integer(1))], [MatrixElement(MatrixSymbol('A', Integer(2), Integer(2)), Integer(1), Integer(0)), MatrixElement(MatrixSymbol('A', Integer(2), Integer(2)), Integer(1), Integer(1))]])"

In [47]: S(srepr(B))                                                                                                                           
Out[47]: 
⎡          6             MatrixElement(A, 0, 1)⎤
⎢                                              ⎥
⎣MatrixElement(A, 1, 0)  MatrixElement(A, 1, 1)⎦
```
