### PR TITLE
Added -q flag in travis.yml file

### LINKED ISSUE #16097: Travis output for failed code quality tests not always informative
After #16023 if a PR fails the code quality test then the only feedback they get from Travis for their whole PR is the log for that job. Looking at this [example though](https://travis-ci.org/sympy/sympy/jobs/499396388) it seems that the output is not always very informative.

The log there ends with:
```
Listing 'sympy/vector/tests'...
Compiling 'sympy/vector/tests/__init__.py'...
Compiling 'sympy/vector/tests/test_coordsysrect.py'...
Compiling 'sympy/vector/tests/test_dyadic.py'...
Compiling 'sympy/vector/tests/test_field_functions.py'...
Compiling 'sympy/vector/tests/test_functions.py'...
Compiling 'sympy/vector/tests/test_operators.py'...
Compiling 'sympy/vector/tests/test_printing.py'...
Compiling 'sympy/vector/tests/test_vector.py'...
Compiling 'sympy/vector/vector.py'...
```
As far as I can tell there is no further output.

I don't understand why though since the script being run should be `bin/test quality` but I get more useful output from that:
```console
$ bin/test quality
====================================================== test process starts =======================================================
executable:         /Users/enojb/current/sympy/venv/bin/python  (3.7.1-final-0) [CPython]
architecture:       64-bit
cache:              yes
ground types:       gmpy 1.17
numpy:              1.16.1
random seed:        52478763
hash randomization: on (PYTHONHASHSEED=2259095863)

sympy/utilities/tests/test_code_quality.py[6] F.....                                                                        [FAIL]

__________________________________________________________________________________________________________________________________
_____________________________________ sympy/utilities/tests/test_code_quality.py:test_files ______________________________________
Traceback (most recent call last):
  File "/Users/enojb/current/sympy/sympy/sympy/utilities/tests/test_code_quality.py", line 242, in test_files
    check_directory_tree(SYMPY_PATH, test, exclude)
  File "/Users/enojb/current/sympy/sympy/sympy/utilities/tests/test_code_quality.py", line 109, in check_directory_tree
    check_files(glob(join(root, pattern)), file_check, exclusions)
  File "/Users/enojb/current/sympy/sympy/sympy/utilities/tests/test_code_quality.py", line 125, in check_files
    file_check(fname)
  File "/Users/enojb/current/sympy/sympy/sympy/utilities/tests/test_code_quality.py", line 146, in test
    test_this_file(fname, test_file)
  File "/Users/enojb/current/sympy/sympy/sympy/utilities/tests/test_code_quality.py", line 176, in test_this_file
    assert False, message_tabs % (fname, idx + 1)
AssertionError: File contains tabs instead of spaces: /Users/enojb/current/sympy/sympy/sympy/core/evalf.py, line 370.

====================================== tests finished: 5 passed, 1 failed, in 0.69 seconds =======================================
DO *NOT* COMMIT!
```

### PR DESCRIPTION
**Pull request by supreet11agrawal**
The -q flags outputs only error messages; reducing the output log.
It makes it easy to understand where the compilation error actually is,
since it outputs where the syntax error occurs

#### References to other Issues or PRs

Fixes #16097 

#### Brief description of what is fixed or changed
-q flag added in compileall line (line no. 261; .travis.yml). Shows only error in output log

#### Other comments
Wasn't sure how to test if it was correct. Ran `python -m compileall -f sympy` in the terminal which showed every compilation steps. `python -m compileall -f -q sympy` showed no such output; just completion of process successfully. Ran `bin/test core` and `bin/test/assumptions` which gave no error.

#### Release Notes

NO ENTRY

### CODE REVIEW

**Comment by oscarbenjamin** [comment]
This looks good.

To demonstrate that this is working can you base another PR off of this one (use a different branch starting from this branch)? In that other PR you can add something like an invalid escape so we can see what the test failure log looks like.

**Comment by supreet11agrawal** [comment]
Ok I will do that once the tests complete.

**Comment by supreet11agrawal** [comment]
I have made some changes in a file which will fail quality test.
To keep it simple, I have used _Tabs_ instead of _Spaces_. Will it do @oscarbenjamin ?

**Comment by jksuom** [comment]
> I have used Tabs instead of Spaces

From PEP 8:

Python 3 disallows mixing the use of tabs and spaces for indentation.

Python 2 code indented with a mixture of tabs and spaces should be converted to using spaces exclusively.

**Comment by jksuom** [comment]
Closed accidentally...

**Comment by supreet11agrawal** [comment]
Locally, it is failing quality tests

**Comment by oscarbenjamin** [comment]
Okay so can you show what the output looks like here?

And then can you submit the failing code in a separate PR with the title "Don't merge: demonstration of -q flag in .travis.yml" referring back to this issue.

**Comment by supreet11agrawal** [comment]
Ok

**Comment by oscarbenjamin** [comment]
I see you've opened #16156 but it doesn't look right for this. You need to add something that will error during compileall. That's the problem we're trying to fix. That's why I suggested an invalid escape.

**Comment by supreet11agrawal** [comment]
@oscarbenjamin where should I add the invalid escape? `compileall` will compile all the `.py` present in a directory. I don't understand how to produce an error in it without provoking an error in quality test.
Locally, I am able to see that `-q` flag is showing only those files in which an error is being generated. But these files are also showing error in quality test as well

**Comment by oscarbenjamin** [comment]
We need Travis to stop at the compileall stop without going on to the quality tests as it did in the example in the issue that this PR fixes.

Tracing back through there this line is the one that caused that error:
[https://github.com/sympy/sympy/commit/d1d15b0905c99968faab6eae3f39a05f1dbedd55#diff-7d3d966eb0a450a4e0289879cbf3182eR59](https://github.com/sympy/sympy/commit/d1d15b0905c99968faab6eae3f39a05f1dbedd55#diff-7d3d966eb0a450a4e0289879cbf3182eR59)

**Comment by oscarbenjamin** [comment]
The main reason for having this compileall step though is to pick up invalid escapes. So you should put try that as well. You can do that with `'\e'`:
```
$ python -We:invalid -m compileall -f t.py 
Compiling 't.py'...
***   File "t.py", line 4
    x = '\e'
       ^
SyntaxError: invalid escape sequence \e
```

**Comment by supreet11agrawal** [comment]
> The main reason for having this compileall step though is to pick up invalid escapes. So you should put try that as well. You can do that with `'\e'`:
> 
> ```
> $ python -We:invalid -m compileall -f t.py 
> Compiling 't.py'...
> ***   File "t.py", line 4
>     x = '\e'
>        ^
> SyntaxError: invalid escape sequence \e
> ```

I have tried putting it as well. Actually, `\e` is not even giving compilation error. :sweat_smile: And whatever change is bringing up the compilation error also fails qulity tests showing invalid syntax

**Comment by oscarbenjamin** [comment]
Which version of Python are you using. I get a compilation error above with 3.7 which is I think what will be used on Travis.

**Comment by supreet11agrawal** [comment]
3.5.6

**Comment by supreet11agrawal** [comment]
Yup, it is working in 3.7. Making PR...

**Comment by supreet11agrawal** [comment]
@oscarbenjamin in my system the quality tests are running but Travis quality tests are failing because of the invalid escape sequence `'\e'` I entered

**Comment by oscarbenjamin** [comment]
Okay this is the log:
[https://travis-ci.org/sympy/sympy/jobs/501150628](https://travis-ci.org/sympy/sympy/jobs/501150628)

The logfile ends with:
```
...
  python -We:invalid -m compileall -f -q sympy/;
  python -We:invalid setup.py -q install;
  pip list --format=columns;
  
*** Error compiling 'sympy/stats/rv_interface.py'...
  File "sympy/stats/rv_interface.py", line 212
    P = '\e'
       ^
SyntaxError: invalid escape sequence \e
```
which is exactly what we want.

Can you reproduce the other example that used tabs?

**Comment by supreet11agrawal** [comment]
> Can you reproduce the other example that used tabs?

I have just made the commit and pushed it

**Comment by supreet11agrawal** [comment]
@oscarbenjamin Is that okay?

**Comment by oscarbenjamin** [comment]
Not yet!

We need to recreate the situation where compileall errors out stopping the build.

I sent a link to the commit that did that above. Maybe it's not working here because you've only used tabs on a comment line.

**Comment by asmeurer** [comment]
Yes please confirm that this still errors on an invalid escape. I had several "false starts" initially addding this test where it wasn't actually catching the errors at all.

**Comment by supreet11agrawal** [comment]
@oscarbenjamin I hope this makes a noticeable difference. I have pushed two commits, with same indentation error; one with a `-q` flag in `.travis.yml` one on without it.
Error log **with** `-q` flag -> https://travis-ci.org/sympy/sympy/jobs/501390423
Error log **without** `-q` flag  -> https://travis-ci.org/sympy/sympy/jobs/501392012
I think it is clear to see that this flag is working in the way we expected it to.

**Comment by oscarbenjamin** [comment]
Yes, that looks good.

I wonder what's going on with the invalid escapes though. Can you demonstrate something similar with them or does compileall not pick them up? That's the reason for having this step in .travis.yml so we need to make sure it's working.

**Comment by supreet11agrawal** [comment]
Invalid escapes are also being cought by`compileall`. See this : https://travis-ci.org/sympy/sympy/jobs/501150628

**Comment by oscarbenjamin** [comment]
Okay then this looks good.

I would merge but I want to @asmeurer to check it as well since this line of code has been problematic in the past. We have to be particular careful when changing the test code because all the other code depends on it...

**Comment by asmeurer** [comment]
I'm not clear where https://github.com/sympy/sympy/commit/68faacdd98ef1db4fb53aa619c18329b077c01fc comes from, but based on the Travis log, this looks correct.
