### ISSUE TITLE
Bugs inverting a matrix of matrix elements

### ISSUE THREAD

**Issue by asmeurer** [sympy/sympy#13541]
```pytb
>>> Matrix(MatrixSymbol('b', 3, 3)).inv()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "./sympy/matrices/matrices.py", line 2797, in inv
    return self._eval_inverse(**kwargs)
  File "./sympy/matrices/dense.py", line 260, in _eval_inverse
    rv = M.inverse_GE(iszerofunc=iszerofunc)
  File "./sympy/matrices/matrices.py", line 2710, in inverse_GE
    red = big.rref(iszerofunc=iszerofunc, simplify=True)[0]
  File "./sympy/matrices/matrices.py", line 889, in rref
    normalize_last=normalize_last)
  File "./sympy/matrices/matrices.py", line 544, in _eval_rref
    zero_above=True)
  File "./sympy/matrices/matrices.py", line 660, in _row_reduce
    get_col(piv_col)[piv_row:], iszerofunc, simpfunc)
  File "./sympy/matrices/matrices.py", line 4130, in _find_reasonable_pivot
    if x.equals(S.Zero):
  File "./sympy/core/expr.py", line 657, in equals
    constant = diff.is_constant(simplify=False, failing_number=True)
  File "./sympy/core/expr.py", line 606, in is_constant
    deriv = expr.diff(w)
  File "./sympy/core/expr.py", line 2967, in diff
    return Derivative(self, *new_symbols, **assumptions)
  File "./sympy/core/function.py", line 1137, in __new__
    if v._diff_wrt:
AttributeError: 'MatrixSymbol' object has no attribute '_diff_wrt'
```

Also, I would expect both of these to work

```pytb
>>> MatrixSymbol('b', 3, 3).inv()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'MatrixSymbol' object has no attribute 'inv'
>>> (MatrixSymbol('b', 3, 3)**-1).as_explicit()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "./sympy/matrices/expressions/matexpr.py", line 299, in as_explicit
    for i in range(self.rows)])
  File "./sympy/matrices/expressions/matexpr.py", line 299, in <listcomp>
    for i in range(self.rows)])
  File "./sympy/matrices/expressions/matexpr.py", line 298, in <listcomp>
    for j in range(self.cols)]
  File "./sympy/matrices/expressions/matexpr.py", line 248, in __getitem__
    return self._entry(i, j)
  File "./sympy/matrices/expressions/matpow.py", line 47, in _entry
    + " of matrix power either not defined or not implemented")
NotImplementedError: (0, 0) entry of matrix power either not defined or not implemented
```

**Comment by vishalg2235** [comment]
First one works fine in my computer.

**Comment by gxyd** [comment]
Can you please verify (using `git bisect`) that indeed this commit https://github.com/sympy/sympy/commit/db19db4b03ba8f6a63d4ce3d48d92e385fb8d371 fixed it?

And also add a test case for this.

**Comment by gxyd** [comment]
I think adding a lower level test case would be better.

**Comment by vishalg2235** [comment]
What is git bisect and how to use it ?

**Comment by asmeurer** [comment]
The `AttributeError: 'MatrixSymbol' object has no attribute 'inv'` one isn't fixed.

**Comment by asmeurer** [comment]
@vishalg2235 see https://stackoverflow.com/questions/4713088/how-to-use-git-bisect. `git bisect` helps you determine which commit in a range caused a change. So you can compare the range of commits between `master` (where it works) and an older commit where it doesn't work (say, the `sympy-1.1.1` tag) to find the commit in between where it was fixed.

**Comment by gxyd** [comment]
> The AttributeError: 'MatrixSymbol' object has no attribute 'inv' one isn't fixed.

Yes I meant only for the first one.

**Comment by vishalg2235** [comment]
Yup. commit https://github.com/sympy/sympy/commit/db19db4b03ba8f6a63d4ce3d48d92e385fb8d371 fixed the issue.

**Comment by vishalg2235** [comment]
`Matrix(MatrixSymbol('b', 3, 3)).inv()` and `MatrixSymbol('b', 3, 3).inv()` should both give same results ? Will this `inv()` also work the same way ?

**Comment by vishalg2235** [comment]
HELP!! many of my files in sympy directory have become `read-only`. Does it has something related with `git bisect`? When I'am saving them it gives error `unable to save '~/git/sympy/sympy/integrals/integrals.py'`. Please help!

**Comment by jksuom** [comment]
Did you run this after `git bisect`?

       After a bisect session, to clean up the bisection state and return to
       the original HEAD (i.e., to quit bisecting), issue the following
       command:

           $ git bisect reset

**Comment by vishalg2235** [comment]
Yes I had run that command

**Comment by jksuom** [comment]
What does `ls -l` show on those read-only files?

**Comment by vishalg2235** [comment]
read only has it's owner "root" and read write files has owner as me
`ls -l` of a read only file gives : 
`-rw-r--r--  1 root   root   11435 Dec 21 21:48 isympy.py
`

**Comment by jksuom** [comment]
If this is not in a system directory, you should change the owner by running `sudo chown -R owner:group path/to/directory` where `owner` and `group` are yours.

**Comment by vishalg2235** [comment]
yes.. It worked.. thanks !!

**Comment by vishalg2235** [comment]
Should I create an `inv` attribute in `MatrixSymbol` that gives same result as `Matrix.inv()`?

**Comment by asmeurer** [comment]
I would define `inv` on the super class `MatrixExpr`, as a shorthand for `self**-1`.

**Comment by vishalg2235** [comment]
```
>>> B = MatrixSymbol(b,2,2)
>>> B**-1
b^-1
```
Means just like above `B.inv()` should give same result `b^-1` ??

**Comment by vishalg2235** [comment]
Ping @asmeurer @jksuom @gxyd .

**Comment by asmeurer** [comment]
The API should be consistent between Matrix and MatrixExpr.

**Comment by vishalg2235** [comment]
>The API should be consistent between Matrix and MatrixExpr.
>
What does this mean ? Does it mean that both should have same functions ?

**Comment by asmeurer** [comment]
Yes
