### PR TITLE
Doc creation now compatible with sphinx 1.3.1.

### LINKED ISSUE #9273: Cannot `make html`
This is what I get (things get interesting with WARNING, at ~80% down):

```
(python2.6.9)jo@jodel:~/Projekte/sympy-workspace/sympy-project/sympy/doc$ git status
Auf Branch improve-sysode-docs
nichts zu committen, Arbeitsverzeichnis unverändert
(python2.6.9)jo@jodel:~/Projekte/sympy-workspace/sympy-project/sympy/doc$ git checkout master
Zu Branch 'master' gewechselt
Ihr Branch ist auf dem selben Stand wie 'origin/master'.
(python2.6.9)jo@jodel:~/Projekte/sympy-workspace/sympy-project/sympy/doc$ make html
Makefile:121: warning: overriding recipe for target '_build/cheatsheet/cheatsheet.pdf'
Makefile:116: warning: ignoring old recipe for target '_build/cheatsheet/cheatsheet.pdf'
rm -rf _build/logo
mkdir -p _build/logo
python ./generate_logos.py -d
INFO:root: File saved: ./_build/logo/sympy-notail.svg
INFO:root: File saved: ./_build/logo/sympy-notailtext.svg
INFO:root: File saved: ./_build/logo/sympy-notext.svg
DEBUG:root:command: rsvg-convert ./src/logo/sympy.svg -f png -o ./_build/logo/sympy-160px.png -h 160 -w 160
DEBUG:root:return code: 0
DEBUG:root:command: rsvg-convert ./src/logo/sympy.svg -f png -o ./_build/logo/sympy-500px.png -h 500 -w 500
DEBUG:root:return code: 0
DEBUG:root:command: rsvg-convert ./_build/logo/sympy-notail.svg -f png -o ./_build/logo/sympy-notail-160px.png -h 160 -w 160
DEBUG:root:return code: 0
DEBUG:root:command: rsvg-convert ./_build/logo/sympy-notail.svg -f png -o ./_build/logo/sympy-notail-500px.png -h 500 -w 500
DEBUG:root:return code: 0
DEBUG:root:command: rsvg-convert ./_build/logo/sympy-notailtext.svg -f png -o ./_build/logo/sympy-notailtext-160px.png -h 160 -w 160
DEBUG:root:return code: 0
DEBUG:root:command: rsvg-convert ./_build/logo/sympy-notailtext.svg -f png -o ./_build/logo/sympy-notailtext-500px.png -h 500 -w 500
DEBUG:root:return code: 0
DEBUG:root:command: rsvg-convert ./_build/logo/sympy-notext.svg -f png -o ./_build/logo/sympy-notext-160px.png -h 160 -w 160
DEBUG:root:return code: 0
DEBUG:root:command: rsvg-convert ./_build/logo/sympy-notext.svg -f png -o ./_build/logo/sympy-notext-500px.png -h 500 -w 500
DEBUG:root:return code: 0
DEBUG:root:command: rsvg-convert ./src/logo/sympy.svg -f png -o ./_build/logo/sympy-16px.png -h 16 -w 16
DEBUG:root:return code: 0
DEBUG:root:command: rsvg-convert ./src/logo/sympy.svg -f png -o ./_build/logo/sympy-32px.png -h 32 -w 32
DEBUG:root:return code: 0
DEBUG:root:command: rsvg-convert ./src/logo/sympy.svg -f png -o ./_build/logo/sympy-48px.png -h 48 -w 48
DEBUG:root:return code: 0
DEBUG:root:command: rsvg-convert ./src/logo/sympy.svg -f png -o ./_build/logo/sympy-64px.png -h 64 -w 64
DEBUG:root:return code: 0
DEBUG:root:command: rsvg-convert ./_build/logo/sympy-notail.svg -f png -o ./_build/logo/sympy-notail-16px.png -h 16 -w 16
DEBUG:root:return code: 0
DEBUG:root:command: rsvg-convert ./_build/logo/sympy-notail.svg -f png -o ./_build/logo/sympy-notail-32px.png -h 32 -w 32
DEBUG:root:return code: 0
DEBUG:root:command: rsvg-convert ./_build/logo/sympy-notail.svg -f png -o ./_build/logo/sympy-notail-48px.png -h 48 -w 48
DEBUG:root:return code: 0
DEBUG:root:command: rsvg-convert ./_build/logo/sympy-notail.svg -f png -o ./_build/logo/sympy-notail-64px.png -h 64 -w 64
DEBUG:root:return code: 0
DEBUG:root:command: rsvg-convert ./_build/logo/sympy-notailtext.svg -f png -o ./_build/logo/sympy-notailtext-16px.png -h 16 -w 16
DEBUG:root:return code: 0
DEBUG:root:command: rsvg-convert ./_build/logo/sympy-notailtext.svg -f png -o ./_build/logo/sympy-notailtext-32px.png -h 32 -w 32
DEBUG:root:return code: 0
DEBUG:root:command: rsvg-convert ./_build/logo/sympy-notailtext.svg -f png -o ./_build/logo/sympy-notailtext-48px.png -h 48 -w 48
DEBUG:root:return code: 0
DEBUG:root:command: rsvg-convert ./_build/logo/sympy-notailtext.svg -f png -o ./_build/logo/sympy-notailtext-64px.png -h 64 -w 64
DEBUG:root:return code: 0
DEBUG:root:command: rsvg-convert ./_build/logo/sympy-notext.svg -f png -o ./_build/logo/sympy-notext-16px.png -h 16 -w 16
DEBUG:root:return code: 0
DEBUG:root:command: rsvg-convert ./_build/logo/sympy-notext.svg -f png -o ./_build/logo/sympy-notext-32px.png -h 32 -w 32
DEBUG:root:return code: 0
DEBUG:root:command: rsvg-convert ./_build/logo/sympy-notext.svg -f png -o ./_build/logo/sympy-notext-48px.png -h 48 -w 48
DEBUG:root:return code: 0
DEBUG:root:command: rsvg-convert ./_build/logo/sympy-notext.svg -f png -o ./_build/logo/sympy-notext-64px.png -h 64 -w 64
DEBUG:root:return code: 0
DEBUG:root:command: convert ./_build/logo/sympy-16px.png ./_build/logo/sympy-32px.png ./_build/logo/sympy-48px.png ./_build/logo/sympy-64px.png ./_build/logo/sympy-favicon.ico
DEBUG:root:return code: 0
DEBUG:root:command: convert ./_build/logo/sympy-notail-16px.png ./_build/logo/sympy-notail-32px.png ./_build/logo/sympy-notail-48px.png ./_build/logo/sympy-notail-64px.png ./_build/logo/sympy-notail-favicon.ico
DEBUG:root:return code: 0
DEBUG:root:command: convert ./_build/logo/sympy-notailtext-16px.png ./_build/logo/sympy-notailtext-32px.png ./_build/logo/sympy-notailtext-48px.png ./_build/logo/sympy-notailtext-64px.png ./_build/logo/sympy-notailtext-favicon.ico
DEBUG:root:return code: 0
DEBUG:root:command: convert ./_build/logo/sympy-notext-16px.png ./_build/logo/sympy-notext-32px.png ./_build/logo/sympy-notext-48px.png ./_build/logo/sympy-notext-64px.png ./_build/logo/sympy-notext-favicon.ico
DEBUG:root:return code: 0

Logo generated.
mkdir -p src/.static
mkdir -p _build/html
mkdir -p _build/doctrees
mkdir -p src/modules
PYTHONPATH=..: sphinx-build -b html -d _build/doctrees  src _build/html
Running Sphinx v1.3
WARNING: the config value 'html_domain_indices' has type `list', defaults to `bool.'
loading pickled environment... not yet created
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 203 source files that are out of date
updating environment: 203 added, 0 changed, 0 removed
reading sources... [100%] wiki                                                                                      
/home/jo/Projekte/sympy-workspace/sympy-project/sympy/doc/src/modules/core.rst:474: WARNING: error while formatting arguments for sympy.core.evalf.N: 'function' object has no attribute '__bases__'
/home/jo/Projekte/sympy-workspace/sympy-project/sympy/doc/src/modules/functions/elementary.rst:306: WARNING: error while formatting arguments for sympy.functions.elementary.miscellaneous.sqrt: 'function' object has no attribute '__bases__'
/home/jo/Projekte/sympy-workspace/sympy-project/sympy/doc/src/modules/polys/internals.rst:749: WARNING: error while formatting arguments for sympy.polys.modulargcd.modgcd_univariate: 'function' object has no attribute '__bases__'
/home/jo/Projekte/sympy-workspace/sympy-project/sympy/doc/src/modules/polys/internals.rst:750: WARNING: error while formatting arguments for sympy.polys.modulargcd.modgcd_bivariate: 'function' object has no attribute '__bases__'
/home/jo/Projekte/sympy-workspace/sympy-project/sympy/doc/src/modules/polys/internals.rst:751: WARNING: error while formatting arguments for sympy.polys.modulargcd.modgcd_multivariate: 'function' object has no attribute '__bases__'
/home/jo/Projekte/sympy-workspace/sympy-project/sympy/doc/src/modules/polys/internals.rst:752: WARNING: error while formatting arguments for sympy.polys.modulargcd.func_field_modgcd: 'function' object has no attribute '__bases__'
looking for now-outdated files... none found
pickling environment... done
checking consistency... done
preparing documents... 
Theme error:
unsupported theme option 'visitedlinkcolor' given
Makefile:50: recipe for target 'html' failed
make: *** [html] Error 1
```

### PR DESCRIPTION
**Pull request by AadityaNair**
Corrected by defining all variables inside the .css file. Closes #9273 
Docs look the same except for the different font when compiled from Sphinx 1.3.1.

What do you think @toolforger @asmeurer.

### CODE REVIEW

**Comment by moorepants** [comment]
Does this still work on versions of Sphinx < 1.3.1?

**Comment by asmeurer** [comment]
Apparently it does, since he didn't update the Travis file, and the tests passed. Or at least they build without errors. It would be good to update it to install the latest version of Sphinx so we can be sure that that builds without errors too.

**Comment by debugger22** [comment]
New font is 'Times new Roman'. It looks worse.

**Comment by asmeurer** [comment]
Can you maybe upload these to some gh-pages so we can see the difference?

**Comment by toolforger** [comment]
Current docs.sympy.org site uses 'sans-serif' as font setting, that gives me a very readable Sans DejaVu.
I guess the new setting is 'serif'. Serif fonts tend to be slower to read, so less suitable for technical content.
You can try putting this into the CSS:
```
body {
    font-family: "sans-serif";
}
```

**Comment by toolforger** [comment]
I found a page on useful font family settings, see http://www.w3schools.com/cssref/css_websafe_fonts.asp .
The line with "Lucida Sans Unicode" seems to be the least Windows-centric good setting.

**Comment by debugger22** [comment]
I like the font used on readthedocs.com. They use 'Lato' for body text and 'Consolas' for source code from Google fonts.

**Comment by debugger22** [comment]
@asmeurer Docs with Times New Roman: http://sympy-docs.s3-website-us-west-2.amazonaws.com/

**Comment by AadityaNair** [comment]
@moorepants I tried it on sphinx v1.2.2 and it works fine.

**Comment by debugger22** [comment]
I built docs with two popular fonts.

Open Sans: http://sympy-docs.s3-website-us-west-2.amazonaws.com/open-sans/gotchas.html
Lato: http://sympy-docs.s3-website-us-west-2.amazonaws.com/lato/gotchas.html

**Comment by AadityaNair** [comment]
@debugger22 I liked the open Sans one.
But I see that you have included the google fonts url int the css file. Their research in multi-agent systems and Game theory and their applications in fields of Artificial Intelligence.

I am fascinated by how AI is used in latest games.Wouldn't that cause problems in offline environments ?

**Comment by debugger22** [comment]
> Their research in multi-agent systems and Game theory and their applications in fields of Artificial Intelligence.
I am fascinated by how AI is used in latest games.

What's this? :)

**Comment by debugger22** [comment]
> Wouldn't that cause problems in offline environments ?

In offline environments it will fallback on system fonts e.g. Arial, etc.

**Comment by toolforger** [comment]
To me, Lato and Open Sans both display as DejaVu (not the sans variant, the serif one).
That's because I don't have either font and the browser fallback is ultimately a serif font.
You can avoid that by adding `, sans-serif` to the `font-family` setting.
Oh, and you can remove the `! important` marker, it's not doing any good. Importance is supposed to be defined in user-provided CSS, not in website-provided CSS.

**Comment by AadityaNair** [comment]
Sorry.
something wrong with my copy-paste system :'(

**Comment by debugger22** [comment]
Yes, I'll add fallback fonts when pushing final changes. `!important` is necessary to override font setting by the theme itself.

**Comment by debugger22** [comment]
> To me, Lato and Open Sans both display as DejaVu (not the sans variant, the serif one).
That's because I don't have either font and the browser fallback is ultimately a serif font.

It shouldn't. The font is being imported from Google fonts.

**Comment by debugger22** [comment]
Sorry, now it's working without `!mportant`. It didn't work the first time I tried, though.

**Comment by toolforger** [comment]
Am 14.04.2015 um 21:43 schrieb Sudhanshu Mishra:
>> To me, Lato and Open Sans both display as DejaVu (not the sans variant, the serif one).
> That's because I don't have either font and the browser fallback is ultimately a serif font.
>
> It shouldn't. The font is being imported from Google fonts.

My Browser isn't allowed to load fonts ;-P

**Comment by asmeurer** [comment]
Is the change of inline code to not be highlighted in gray something you did or part of the Sphinx update?

**Comment by AadityaNair** [comment]
I think it is  an issue with the sphinx update. Highlighting works with sphinx v1.2.2

**Comment by asmeurer** [comment]
I'm not strictly opposed to removing the highlighting, but if we do, we should make sure to choose regular and monospace fonts that are easily distinguishable from one another to avoid confusion.

**Comment by debugger22** [comment]
I couldn't find it in their changelog. I've created an issues https://github.com/sphinx-doc/sphinx/issues/1848 for that.

**Comment by debugger22** [comment]
One other workaround would be to add a `background-color` to the classname `docutils literal`.

**Comment by debugger22** [comment]
Fixed the highlighting. http://sympy-docs.s3-website-us-west-2.amazonaws.com/open-sans/new/

CSS: https://github.com/debugger22/sympy/commit/56e1bc8e0a22e577d70e8082e0999bdf9d1df0fc

**Comment by debugger22** [comment]
Looks like there's some issue with this version on Travis. https://github.com/sphinx-doc/sphinx/issues/814

**Comment by AadityaNair** [comment]
Should we consider the failed test a problem ?
It is just a warning and the docs *are* getting created.

**Comment by toolforger** [comment]
If we start ignoring that failure, we won't be alerted when a commit newly creates a real problem.
So we can't just ignore it, it needs to be fixed.

I got the reason: `sympy.core.evalf` declares `N` to be a function, but `doc/src/modules/core.rst:469` says `autoclass`.

**Comment by debugger22** [comment]
@AadityaNair Could you try the change suggested by @toolforger. Replace `autoclass` with `autofunction` and see if it works.

**Comment by AadityaNair** [comment]
sure
