### ISSUE TITLE
AttributeError in integral

### ISSUE THREAD

**Issue by oscarbenjamin** [sympy/sympy#23707]
```python
In [1]: integrate(exp(t)*exp(-t*sqrt(x - y)), t)
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-1-84e3ec3316fd> in <module>
----> 1 integrate(exp(t)*exp(-t*sqrt(x - y)), t)

~/current/sympy/sympy.git/sympy/integrals/integrals.py in integrate(meijerg, conds, risch, heurisch, manual, *args, **kwargs)
   1565 
   1566     if isinstance(integral, Integral):
-> 1567         return integral.doit(**doit_flags)
   1568     else:
   1569         new_args = [a.doit(**doit_flags) if isinstance(a, Integral) else a

~/current/sympy/sympy.git/sympy/integrals/integrals.py in doit(self, **hints)
    610                     antideriv = None
    611                 else:
--> 612                     antideriv = self._eval_integral(
    613                         function, xab[0], **eval_kwargs)
    614                     if antideriv is None and meijerg is True:

~/current/sympy/sympy.git/sympy/integrals/integrals.py in _eval_integral(self, f, x, meijerg, risch, manual, heurisch, conds, final)
   1082                     try:
   1083                         if conds == 'piecewise':
-> 1084                             h = heurisch_wrapper(g, x, hints=[])
   1085                         else:
   1086                             h = heurisch_(g, x, hints=[])

~/current/sympy/sympy.git/sympy/integrals/heurisch.py in heurisch_wrapper(f, x, rewrite, hints, mappings, retries, degree_offset, unnecessary_permutations, _try_heurisch)
    151     for d in denoms(res):
    152         try:
--> 153             slns += solve(d, dict=True, exclude=(x,))
    154         except NotImplementedError:
    155             pass

~/current/sympy/sympy.git/sympy/solvers/solvers.py in solve(f, *symbols, **flags)
   1115     ###########################################################################
   1116     if bare_f:
-> 1117         solution = _solve(f[0], *symbols, **flags)
   1118     else:
   1119         solution = _solve_system(f, symbols, **flags)

~/current/sympy/sympy.git/sympy/solvers/solvers.py in _solve(f, *symbols, **flags)
   1387         for s in nonlin_s:
   1388             try:
-> 1389                 soln = _solve(f, s, **flags)
   1390                 for sol in soln:
   1391                     if sol.free_symbols & got_s:

~/current/sympy/sympy.git/sympy/solvers/solvers.py in _solve(f, *symbols, **flags)
   1713         if flags.pop('_unrad', True):
   1714             try:
-> 1715                 u = unrad(f_num, symbol)
   1716             except (ValueError, NotImplementedError):
   1717                 u = False

~/current/sympy/sympy.git/sympy/solvers/solvers.py in unrad(eq, *syms, **flags)
   3376                 bases.add(g.base)
   3377         return rads, bases, lcm
-> 3378     rads, bases, lcm = _rads_bases_lcm(poly)
   3379 
   3380     covsym = Dummy('p', nonnegative=True)

~/current/sympy/sympy.git/sympy/solvers/solvers.py in _rads_bases_lcm(poly)
   3369         rads = set()
   3370         bases = set()
-> 3371         for g in poly.gens:
   3372             q = _Q(g)
   3373             if q != 1:

AttributeError: 'NoneType' object has no attribute 'gens'
```

**Comment by oscarbenjamin** [comment]
This integral previously succeeded but stopped working in 2e4fbdaf852eeee54dcdcbd705696cb4ba969c48 from #22539

**Comment by oscarbenjamin** [comment]
This is due to:
```python
In [1]: solve(sqrt(x - y)*exp(t*sqrt(x - y)) - exp(t*sqrt(x - y)), y)
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-1-a3443b0483fc> in <module>
----> 1 solve(sqrt(x - y)*exp(t*sqrt(x - y)) - exp(t*sqrt(x - y)), y)

~/current/sympy/sympy.git/sympy/solvers/solvers.py in solve(f, *symbols, **flags)
   1117     ###########################################################################
   1118     if bare_f:
-> 1119         solution = _solve(f[0], *symbols, **flags)
   1120     else:
   1121         solution = _solve_system(f, symbols, **flags)

~/current/sympy/sympy.git/sympy/solvers/solvers.py in _solve(f, *symbols, **flags)
   1715         if flags.pop('_unrad', True):
   1716             try:
-> 1717                 u = unrad(f_num, symbol)
   1718             except (ValueError, NotImplementedError):
   1719                 u = False

~/current/sympy/sympy.git/sympy/solvers/solvers.py in unrad(eq, *syms, **flags)
   3378                 bases.add(g.base)
   3379         return rads, bases, lcm
-> 3380     rads, bases, lcm = _rads_bases_lcm(poly)
   3381 
   3382     covsym = Dummy('p', nonnegative=True)

~/current/sympy/sympy.git/sympy/solvers/solvers.py in _rads_bases_lcm(poly)
   3371         rads = set()
   3372         bases = set()
-> 3373         for g in poly.gens:
   3374             q = _Q(g)
   3375             if q != 1:

AttributeError: 'NoneType' object has no attribute 'gens'
```
