### PR TITLE
Tweak .core.relational._canoncial_coeff to fix gh-27538

### LINKED ISSUE #27538: Regression in Piecewise when xreplacing involing a Relational (sympy-1.9 -- sympy-1.10)
Here's a script to find the regression:
```bash
#!/bin/bash                                                                                                                                                                                                                                                                   
cat <<EOF >bisect-regression.py                                                                                                                                                                                                                                               
from sympy import symbols, Piecewise, Equality, true                                                                                                                                                                                                                          
x, y = symbols('x, y')                                                                                                                                                                                                                                                        
p1 = Piecewise(                                                                                                                                                                                                                                                               
    (0, Equality(x, true)),                                                                                                                                                                                                                                                   
    (1, true),                                                                                                                                                                                                                                                                
)                                                                                                                                                                                                                                                                             
p2 = p1.xreplace({x: y < 1})                                                                                                                                                                                                                                                  
assert p2.subs(y, 0) == 0                                                                                                                                                                                                                                                     
assert p2.subs(y, 1) == 1                                                                                                                                                                                                                                                     
EOF                                                                                                                                                                                                                                                                           
git bisect start --first-parent sympy-1.10 sympy-1.9                                                                                                                                                                                                                          
git bisect run python bisect-regression.py
```

<details>
<summary>$ ./bisect-regression.sh</summary>


```
[930efd2907a9d6c15500e0aa3d5507691dbb297b] Merge pull request #22358 from PGijsbers/18521_limits
running  'python' 'bisect-regression.py'
4282433901d3159a485866ce0d93aefe531ffbc7 is the first bad commit
commit 4282433901d3159a485866ce0d93aefe531ffbc7
Merge: 930efd2907 d02946955f
Author: Christopher Smith <smichr@gmail.com>
Date:   Sun Oct 24 04:20:27 2021 -0500

    Merge pull request #22286 from smichr/pwmeij
    
    modify _condsimp to handle missed cases; remove expensive steps from Piecewise.eval
```

</details>
It identifies gh-22286 as the PR introducing the regression (I don't blame anyone for that of course, our test coverage isn't always the best).

One way to resolve this would be to patch `_canonical_coeff` in `.core.relational` (introduced in the referenced PR), so that it handles `Relational`s with `BooleanTrue`/`BooleanFalse` in either `lhs` or `rhs`. But if someone knows a better way, let me know, otherwise I'll try to whip up a PR doing just that.

### PR DESCRIPTION
**Pull request by bjodah**
#### References to other Issues or PRs
Fixes #27538

#### Brief description of what is fixed or changed
Fixes a regression involving Piecewise and Relationals:
```console-session
  File "/opt-3/cpython-v3.12-apt-deb/lib/python3.12/site-packages/sympy/core/relational.py", line 55, in _canonical_coeff
    b, l = rel.lhs.as_coeff_Add(rational=True)
           ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'BooleanTrue' object has no attribute 'as_coeff_Add'
```

#### Other comments
Since `rel.rhs.is_Boolean` was probed I'm thinking the smallest change to be made here was to make the same check on `rel.lhs`, and return the reverse of the `Relational` if it's true (reversing in the name of canonicalization).

#### Release Notes

NO ENTRY

### CODE REVIEW

File: sympy/core/relational.py [hunk 1]
```diff
@@ -52,6 +52,8 @@ def _canonical_coeff(rel):
     rel = rel.canonical
     if not rel.is_Relational or rel.rhs.is_Boolean:
         return rel  # Eq(x, True)
+    if rel.lhs.is_Boolean:
+        return rel.reversed  # e.g.: Eq(True, x) -> Eq(x, True)
```
Comment (oscarbenjamin) [inline sympy/core/relational.py:56]: I think it would be better to check for `Expr` here rather than `Boolean`.

Comment (bjodah) [reply sympy/core/relational.py:56]: Alright, I opened an alternative PR (to let these tests run to completion, and cleaner commit history upon merge):
gh-27541

**Comment by oscarbenjamin** [comment]
Closing as the alternative https://github.com/sympy/sympy/pull/27541 was merged.
