### PR TITLE
``differentiate_finite`` for expressions with embedded derivatives

### LINKED ISSUE #17209: differentiate_finite gives wrong results for expressions with embedded derivatives
The `differentiate_finite` function works great for expressions that do not include any derivatives (like expressions in the [Sympy Tutorial](https://docs.sympy.org/latest/tutorial/calculus.html)), however when more complex expressions are used the `differentiate_finite` discretizes expressions in a wrong way.

If we want to use `differentiate_finite` to make finite difference of expressions that including functions and derivatives, e.g., `expr = nu(y)*diff(U(y), y)`, one would write

```
from sympy import *
y = Symbol('y') 
dy, U, nu = symbols('dy U nu', cls=Function)
df_expr = differentiate_finite(nu(y)*diff(U(y), y), y, points=dy(y))
```

Note that I am also trying to make dy = dy(y), which is common when making finite differences on stretched grids. Executing the code above does not lead to proper discretization. The proper discratization for the above expression should be

```assert (df_true - df_expr).simplify() 
df_true = nu(y+dy(y)/2)*(U(y+dy(y))/dy(y+dy(y)/2)-U(y)/dy(y+dy(y)/2))/dy(y) - nu(y-dy(y)/2)*(U(y)/dy(y-dy(y)/2)-U(y-dy(y))/dy(y-dy(y)/2))/dy(y)
```

I am extremely sorry for the poor readability of these expressions. Nevertheless, if this was made a test `assert (df_expr - df_true).simplify() == 0` would fail.

The problem as I see, is that `differentiate_finite` replaces the embedded derivatives with finite derivatives at the wrong `x0` locations. In order to have correct discretization of expressions with embedded derivatives the `x0` for embedded derivatives should depend on the `x0` and `points` arguments of the outer derivative.

What do you think about it?

### PR DESCRIPTION
**Pull request by vezeli**
#### References to other Issues or PRs

Closely related to #17248

#### Brief description of what is fixed or changed

Fixes #17209

This PR corrects the behavior of ``differentiate_finite`` so that it works for expressions with embedded derivatives. Previously, if derivatives were present in the argument of ``differentiate_finite`` the algorithm would simply replace the derivatives with finite differences at wrong locations (see #17209):

```
>>> from sympy import *
>>> x = Symbol('x')
>>> f, g = Function('f'), Function('g')
>>> df_expr = differentiate_finite(f(x)*g(x).diff(x), x)
>>> df_expr
-(-g(x - 1/2) + g(x + 1/2))*f(x - 1/2) + (-g(x - 1/2) + g(x + 1/2))*f(x + 1/2)
```

In this case, both `f(x)` and `g(x).diff(x)` are discretized around the same point which is wrong because `g(x).diff(x)` should be discretized around the point where `f(x)` is discretized, i.e., either `x + 1/2` or `x - 1/2`.

New algorithm takes this into an account and corrects this so that the result of the previous code block would be `(-g(x) + g(x + 1))*f(x + 1/2) - (g(x) - g(x - 1))*f(x - 1/2)` which is the right solution.

Added documentation and tests.

#### Other comments

* Backwards compatibility is preserved for expressions without embedded derivatives that use ``evaluate=True`` (however, as the documentation clearly states, in most of the cases this is not what users would like).

* Algorithm works for higher order derivatives and this feature is tested in `sympy/calculus/tests/test_finite_difference.py`.

* Together with #17248 ``differentiate_finite`` can be used for discretizing expressions with non-constant step using undefined functions. This is also documented.

#### Release Notes

* calculus
  * Correct the solution of ``differentiate_finite`` for expressions that contain embedded derivatives.
  * Deprecated ``evaluate`` argument in ``differentiate_finite`` for making non-conservative finite differences.

### CODE REVIEW

File: sympy/calculus/finite_diff.py [hunk 1]
```diff
@@ -452,32 +450,51 @@ def differentiate_finite(expr, *symbols,
...
     f(x - 1/2, y - 1/2) - f(x - 1/2, y + 1/2) - f(x + 1/2, y - 1/2) + f(x + 1/2, y + 1/2)
+    >>> differentiate_finite(f(x)*g(x).diff(x), x)
+    (-g(x) + g(x + 1))*f(x + 1/2) - (g(x) - g(x - 1))*f(x - 1/2)
+
+    To make finite difference with non-constant discretization step use
+    undefined functions:
+
+    >>> dx = Function('dx')
+    >>> differentiate_finite(f(x)*g(x).diff(x), points=dx(x))
+    -(-g(x - dx(x)/2 - dx(x - dx(x)/2)/2)/dx(x - dx(x)/2) + g(x - dx(x)/2 + dx(x - dx(x)/2)/2)/dx(x - dx(x)/2))*f(x - dx(x)/2)/dx(x) + (-g(x + dx(x)/2 - dx(x + dx(x)/2)/2)/dx(x + dx(x)/2) + g(x + dx(x)/2 + dx(x + dx(x)/2)/2)/dx(x + dx(x)/2))*f(x + dx(x)/2)/dx(x)
```
Comment (asmeurer) [inline sympy/calculus/finite_diff.py]: You should be able to line wrap this.

Comment (vezeli) [reply sympy/calculus/finite_diff.py]: My thoughts exactly and if you look at the previous commits I tried to wrap it but the doctest was failing. The problem is that after 2a219e7bc4f7a5ecefc99f49128601d82b844e94 docstring `differentiate_finite.__doc__` was changed to raw string and line break `\` doesn't seem to work now. How does one wrap lines in the case of raw strings?

Another way would be to change the docstring to standard string again and use `\`. What do you think?

Comment (oscarbenjamin) [reply sympy/calculus/finite_diff.py]: Have you tried just wrapping it? The doctest runner should handle variable whitespace

Comment (vezeli) [reply sympy/calculus/finite_diff.py]: @oscarbenjamin I did, take a look at the previous commit c690901ea822cea. The line was wrapped as following
```python
    >>> dx = Function('dx')
    >>> differentiate_finite(f(x)*g(x).diff(x), points=dx(x))
    -(-g(x - dx(x)/2 - dx(x - dx(x)/2)/2)/dx(x - dx(x)/2) \
+ g(x - dx(x)/2 + dx(x - dx(x)/2)/2)/dx(x - dx(x)/2))*f(x - dx(x)/2)/dx(x) \
+ (-g(x + dx(x)/2 - dx(x + dx(x)/2)/2)/dx(x + dx(x)/2) \
+ g(x + dx(x)/2 + dx(x + dx(x)/2)/2)/dx(x + dx(x)/2))*f(x + dx(x)/2)/dx(x)
```
and the doctest failed. Is that what you meant?

Comment (oscarbenjamin) [reply sympy/calculus/finite_diff.py]: Have you tried without the slashes?

Comment (vezeli) [reply sympy/calculus/finite_diff.py]: @oscarbenjamin Yes, the latest commit e2e0f28d57b is without slashes but it is failing.

Is there possibility to move from raw string `r"""` to standard docstring `"""` than wrapping would work, would that be a possibility? Or are there any other ideas that might work?

**Comment by vezeli** [comment]
@asmeurer @oscarbenjamin The doc is wrapped now.

File: sympy/calculus/finite_diff.py (hunk 1 above)
Comment (vezeli) [reply sympy/calculus/finite_diff.py]: @asmeurer @oscarbenjamin The doc is wrapped now.

Comment (oscarbenjamin) [reply sympy/calculus/finite_diff.py]: I meant that you should be able to wrap it like this:
```diff
diff --git a/sympy/calculus/finite_diff.py b/sympy/calculus/finite_diff.py
index d6c24e72ea..4f62a42b04 100644
--- a/sympy/calculus/finite_diff.py
+++ b/sympy/calculus/finite_diff.py
@@ -474,10 +474,10 @@ def differentiate_finite(expr, *symbols,
 
     >>> dx = Function('dx')
     >>> differentiate_finite(f(x)*g(x).diff(x), points=dx(x))
-    -(-g(x - dx(x)/2 - dx(x - dx(x)/2)/2)/dx(x - dx(x)/2) + \
-g(x - dx(x)/2 + dx(x - dx(x)/2)/2)/dx(x - dx(x)/2))*f(x - dx(x)/2)/dx(x) + \
-(-g(x + dx(x)/2 - dx(x + dx(x)/2)/2)/dx(x + dx(x)/2) + \
-g(x + dx(x)/2 + dx(x + dx(x)/2)/2)/dx(x + dx(x)/2))*f(x + dx(x)/2)/dx(x)
+    -(-g(x - dx(x)/2 - dx(x - dx(x)/2)/2)/dx(x - dx(x)/2) +
+    g(x - dx(x)/2 + dx(x - dx(x)/2)/2)/dx(x - dx(x)/2))*f(x - dx(x)/2)/dx(x) +
+    (-g(x + dx(x)/2 - dx(x + dx(x)/2)/2)/dx(x + dx(x)/2) +
+    g(x + dx(x)/2 + dx(x + dx(x)/2)/2)/dx(x + dx(x)/2))*f(x + dx(x)/2)/dx(x)
 
     """
     # Key-word only arguments only available in Python 3
```
Whether it is a raw string or not shouldn't matter.

**Comment by oscarbenjamin** [comment]
In what sense are the results from this PR better than the previous results? Are they more accurate? Were the previous results just plain wrong?

**Comment by vezeli** [comment]
The previous results were correct only for discretization of simple expressions like _f(x)*g(x)_. However, if one tries to use the previous code to discretize functions with embedded derivatives _f(x)*g(x).diff(x)_ than the code gives wrong results.

The new results extend the applicability of the ``differentiate_finite`` so it can be used together with argument expressions that contain more complex functions (like embedded derivatives _f(x)*g(x).diff(x)_).

File: sympy/calculus/tests/test_finite_diff.py [hunk 2]
```diff
@@ -142,3 +142,12 @@ def test_differentiate_finite():
...
                                                     pints=[x-1, x+1]))
+
+    res3 = differentiate_finite(f(x)*g(x).diff(x), x)
+    ref3 = (-g(x) + g(x + 1))*f(x + S.Half) - (g(x) - g(x - 1))*f(x - S.Half)
+    assert (res3 - ref3).simplify() == 0
+
+    res4 = differentiate_finite(f(x)*g(x).diff(x).diff(x), x)
+    ref4 = -(g(x - Rational(3, 2)) - 2*g(x - S.Half) + g(x + S.Half))*f(x - S.Half) \
+           + (g(x - S.Half) - 2*g(x + S.Half) + g(x + Rational(3, 2)))*f(x + S.Half)
+    assert (res4 - ref4).simplify() == 0
```
Comment (oscarbenjamin) [inline sympy/calculus/tests/test_finite_diff.py]: I guess the simplify here is just to distribute the minus signs. If you put brackets around every except the minus it will work without simplify:
```
-((g(x - Rational(3, 2)) - 2*g(x - S.Half) + g(x + S.Half))*f(x - S.Half))
```
Otherwise if it's just for the signs then signsimp should be used. General simplify should be avoided in tests.

**Comment by oscarbenjamin** [comment]
I see that the results on master are plain incorrect. Here is a more dramatic example:
```julia
In [1]: differentiate_finite(f(x).diff(x)*g(x).diff(x), x)                                                                           
Out[1]: 0
```

**Comment by vezeli** [comment]
@oscarbenjamin that one is scary. Result on the PR branch, for the same example, gives
```
In [3]: differentiate_finite(f(x).diff(x)*g(x).diff(x), x)                                                                                                            
Out[3]: (-f(x) + f(x + 1))*(-g(x) + g(x + 1)) - (f(x) - f(x - 1))*(g(x) - g(x - 1))
```
which should be correct.

**Comment by oscarbenjamin** [comment]
You can test that it is correct with:
```julia
In [6]: differentiate_finite(f(x).diff(x)*g(x).diff(x), points=[x-h, x, x+h])                                                     
Out[6]: 
⎛  2⋅f(x)   f(-h + x)   3⋅f(h + x)⎞ ⎛  2⋅g(x)   g(-h + x)   3⋅g(h + x)⎞   ⎛2⋅f(x)   3⋅f(-h + x)   f(h + x)⎞ ⎛2⋅g(x)   3⋅g(-h + x
⎜- ────── + ───────── + ──────────⎟⋅⎜- ────── + ───────── + ──────────⎟   ⎜────── - ─────────── - ────────⎟⋅⎜────── - ──────────
⎝    h         2⋅h         2⋅h    ⎠ ⎝    h         2⋅h         2⋅h    ⎠   ⎝  h          2⋅h         2⋅h   ⎠ ⎝  h          2⋅h   
─────────────────────────────────────────────────────────────────────── - ──────────────────────────────────────────────────────
                                  2⋅h                                                                     2⋅h                   

)   g(h + x)⎞
─ - ────────⎟
      2⋅h   ⎠
─────────────
             

In [7]: _.limit(h, 0).doit()                                                                                                      
Out[7]: 
           2           2               
d         d           d        d       
──(f(x))⋅───(g(x)) + ───(f(x))⋅──(g(x))
dx         2           2       dx      
         dx          dx  
```
Maybe it's worth using something like that in the tests.

**Comment by oscarbenjamin** [comment]
I find `differentiate_finite` to be an odd API. If the purpose is to apply numeric differentiation to all derivatives in an expression then that makes sense but why does it also need to be for the derivative of the input expression rather than the expression itself? Alternatively if the purpose is to compute a numeric approximation of the derivative of the expression starting from the premise that the input expression is known that why is it applying numerical differentiation to derivatives within the expression?

This PR looks good but I'd like to see more tests and the tests don't need to use simplify.

File: sympy/calculus/finite_diff.py [hunk 3]
```diff
@@ -452,32 +450,54 @@ def differentiate_finite(expr, *symbols,
...
+    g(x + dx(x)/2 + dx(x + dx(x)/2)/2)/dx(x + dx(x)/2))*f(x + dx(x)/2)/dx(x)
 
     """
     # Key-word only arguments only available in Python 3
     points = kwargs.pop('points', 1)
     x0 = kwargs.pop('x0', None)
     wrt = kwargs.pop('wrt', None)
     evaluate = kwargs.pop('evaluate', False)
+    if any(term.is_Derivative for term in list(preorder_traversal(expr))):
+        evaluate = False
```
Comment (kenluck2001) [inline sympy/calculus/finite_diff.py]: When is evaluate ever set to True. It seems you set to it to False if you have any term that does not have a derivative.

**Comment by vezeli** [comment]
@oscarbenjamin `differentiate_finite` was introduced in 372f89d however it doesn't say what is the motivation behind the function. I think it is due to the fact that ``Derivative.as_finite_difference()`` does not work for expressions that can be expanded, e.g.,

```
In[8]: diff(f(x)*g(x), x).as_finite_difference()
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-14-01b7c4833c73> in <module>
----> 1 (diff(f(x)*g(x), x)).as_finite_difference()

AttributeError: 'Add' object has no attribute 'as_finite_difference'
```

and `diff(f(x)*g(x))` by default expands into `f(x)*Derivative(g(x), x) + g(x)*Derivative(f(x), x)` so there is need for `differentiate_finite` or modifying `as_finite_difference` method...

Thanks for the input, I really like the idea with using limes for testing, very creative. I'll submit as soon as I make the changes.

File: sympy/calculus/finite_diff.py (hunk 3 above)
Comment (vezeli) [reply sympy/calculus/finite_diff.py]: I don't really see the use case when one wants to set it True and that is stated in the documentation as well  

>    Note that the above form preserves the product rule in discrete form. If we
>    want we can pass ``evaluate=True`` to get another form (which is usually
>    not what we want):

However, I decided to leave because maybe someone is relying on it and I didin't want to beak backwards compatibility. This means, if needed, one can still use `evaluate=True` for expressions without derivatives inside them

```
In[3]: differentiate_finite(f(x)*g(x), x, evaluate=True)
Out[3]: (-f(x - 1/2) + f(x + 1/2))*g(x) + (-g(x - 1/2) + g(x + 1/2))*f(x)

In [4]: differentiate_finite(f(x)*g(x), x, evaluate=False)                                                                                                           
Out[4]: -f(x - 1/2)*g(x - 1/2) + f(x + 1/2)*g(x + 1/2)
```

File: sympy/calculus/tests/test_finite_diff.py [hunk 4]
```diff
@@ -142,3 +142,18 @@ def test_differentiate_finite():
     assert (res2 - ref2).simplify() == 0
     raises(ValueError, lambda: differentiate_finite(f(x)*g(x), x,
                                                     pints=[x-1, x+1]))
+
+    res3 = differentiate_finite(f(x)*g(x).diff(x), x)
+    ref3 = (-g(x) + g(x + 1))*f(x + S.Half) - (g(x) - g(x - 1))*f(x - S.Half)
+    assert (res3 - ref3).simplify() == 0
```
Comment (oscarbenjamin) [inline sympy/calculus/tests/test_finite_diff.py]: This should just be `assert res3 == ref3` (same for others below)

We generally prefer not to use simplify in test output and it isn't needed in this case.

File: sympy/calculus/tests/test_finite_diff.py [hunk 5]
```diff
@@ -142,3 +142,18 @@ def test_differentiate_finite():
...
+
+    res4 = differentiate_finite(f(x)*g(x).diff(x).diff(x), x)
+    ref4 = -((g(x - Rational(3, 2)) - 2*g(x - S.Half) + g(x + S.Half))*f(x - S.Half)) \
+           + (g(x - S.Half) - 2*g(x + S.Half) + g(x + Rational(3, 2)))*f(x + S.Half)
+    assert res4 - ref4 == 0
+
+    res5_expr = f(x).diff(x)*g(x).diff(x)
+    res5 = diff(res5_expr, x)
+    ref5_ = differentiate_finite(res5_expr, points=[x-h, x, x+h])
+    ref5 = ref5_.limit(h, 0).doit()
```
Comment (oscarbenjamin) [inline sympy/calculus/tests/test_finite_diff.py]: Can we also explicitly spell out what the answer is before taking the limit and test that

File: sympy/calculus/finite_diff.py (hunk 3 above)
Comment (oscarbenjamin) [reply sympy/calculus/finite_diff.py]: Is the `evaluate=True` behaviour actually useful or should it be deprecated?

Comment (vezeli) [reply sympy/calculus/finite_diff.py]: I didn't want to open this discussion or make that call but since you mentioned it... I don't see `evaluate=True` so useful... Expressions passed to `differentiate_finite` are usually in the form in which they should be discretized, I don't think this function should manipulate expressions before discretization in any way.

Comment (oscarbenjamin) [reply sympy/calculus/finite_diff.py]: @bjodah What is the purpose of `evaluate=True` in `differentiate_finite`. It seems to be discouraged in the docstring. Should it be deprecated and removed?

Comment (bjodah) [reply sympy/calculus/finite_diff.py]: I can't remember I'm afraid. I think we introduced it for backwards compatibility reasons. I'm fine with deprecating it.

Comment (oscarbenjamin) [reply sympy/calculus/finite_diff.py]: @vezeli can you add a deprecation warning for the `evaluate` flag and update the docstring?

Comment (vezeli) [reply sympy/calculus/finite_diff.py]: @oscarbenjamin It seems like the PR is in line with the wisdom of [Zen of SymPy](https://github.com/sympy/sympy/blob/master/sympy/this.py):

> Unevaluated is better than evaluated.

Additionally, I changed the docstrings in other functions that were not correctly leveled.

**Comment by oscarbenjamin** [comment]
It looks like the other tests will need rearranging to test the deprecated behaviour.

There is the `ignore_warnings` context manager in `sympy/utilities/pytest.py` that can be used to suppress warnings while testing deprecated functionality.

**Comment by vezeli** [comment]
@oscarbenjamin sorry for the long delay... can we continue with this? can you please guide me so that this gets fixed?

**Comment by oscarbenjamin** [comment]
The flake8 test has failed because of an unneeded import.

**Comment by vezeli** [comment]
But than when I remove it I get errors that these are undefined... How do I make it happy?

**Comment by oscarbenjamin** [comment]
You can test locally with flake8 yourself.

You just need to make sure that each name used in the file is imported exactly once and that the name isn't imported if it isn't used.

Right now there are missing imports which you would also see if you run the tests for this file locally.

**Comment by vezeli** [comment]
@oscarbenjamin could you provide a hint here, there are no problems with flake8 and tests only doctests... I am not sure I understand why this one is not working?

**Comment by oscarbenjamin** [comment]
Note also that you can run the doctests locally:
```
$ bin/doctest sympy/calculus/finite_diff.py
```
I'm not sure but I think the problem is that you've put a line break in after a `/` but there is no whitespace there in the raw output of the doctest example.

**Comment by vezeli** [comment]
OK, I managed to make it pass the tests. I removed the part of tutorial using `evaluate` as it doesn't have use-case any longer.

**Comment by oscarbenjamin** [comment]
This looks good except for the release note in the OP at the top of the PR. There should be another note explaining the deprecation. I'm not sure exactly how to describe it though...

**Comment by vezeli** [comment]
@oscarbenjamin What is the status of this PR now?

**Comment by oscarbenjamin** [comment]
This looks good. Thanks!
