### ISSUE TITLE
Multiplying a vector by float zero raises an error.

### ISSUE THREAD

**Issue by Vrekrer** [sympy/sympy#27963]
```
from sympy.vector import CoordSys3D
N = CoordSys3D('N')

N.i*0   # This works fine
N.i*0.0 # This raises: AttributeError: 'Zero' object has no attribute '_base_instance'
```
This bug has been present since release 1.13.0 and is still present in 1.14.0rc1. The above code works fine in SymPy 1.12.1.

**Comment by oscarbenjamin** [comment]
I bisected it to 7868f75a310644e792f95dbbb0ce0e2bc3713b6c from https://github.com/sympy/sympy/pull/25614.

That changed the way that floats and rational compare.

This is a simple fix:
```diff
diff --git a/sympy/vector/basisdependent.py b/sympy/vector/basisdependent.py
index 53e4efc0bf..c69e943204 100644
--- a/sympy/vector/basisdependent.py
+++ b/sympy/vector/basisdependent.py
@@ -258,7 +258,7 @@ def _new(cls, *args, **options):
             if isinstance(arg, cls._zero_func):
                 count += 1
                 zeroflag = True
-            elif arg == S.Zero:
+            elif arg == S.Zero or arg == 0.0:
                 zeroflag = True
             elif isinstance(arg, (cls._base_func, cls._mul_func)):
                 count += 1
```
Alternatively the `equal_valued` function from `sympy/core/numbers.py` could be used. I guess there should be something specifically for testing for zero.
