### PR TITLE
maint: bump version to 1.12.1

### PR DESCRIPTION
**Pull request by oscarbenjamin**
#### References to other Issues or PRs

See gh-25837 and https://github.com/sympy/sympy/pull/25855#issuecomment-1788823737

A SymPy 1.12.1 release is needed to backport the fix in gh-25224 for compatibility with Python 3.12.

- [X] Backported gh-25224 (parsing ast)
- [X] Backported gh-25184 (parsing ast)
- [x] Backported gh-25286 (py2-import CI)
- [x] Backported gh-25249 to fix the sphinx build.
- [x] Backported gh-25562 and gh-25562 for the benchmarks.
- [x] Backported gh-25290 for compatibility with future mpmath (1.4.0?)
- [x] Backported gh-25255 (deprecated `~bool`)
- [ ] Copy over release notes

The release notes need to be copied into the Wiki manually:
```
* parsing
    * Fix parsing issues for after changes in the stdlib ast module so that `sympify` and `parse_expr` will work in Python 3.12.
* other
    * Fix sphinx build for Sphinx 7.2
* logic
    * Remove deprecated use of `~bool` in logic for compatibility with Python 3.12.
```

#### Brief description of what is fixed or changed

Bump version to 1.12.1 Update the 1.12 branch with respect to changes in various dependencies. Fixes `parse_expr` for Python 3.12 after changes in the stdlib ast module.

#### Release Notes

NO ENTRY

### CODE REVIEW

**Comment by tornaria** [comment]
Is 1.12.1 here released? The recent pre-release of mpmath 1.4.0a0 breaks sympy-1.12:
```
$ python -c 'import sympy'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python3.12/site-packages/sympy/__init__.py", line 30, in <module>
    from sympy.core.cache import lazy_function
  File "/usr/lib/python3.12/site-packages/sympy/core/__init__.py", line 9, in <module>
    from .expr import Expr, AtomicExpr, UnevaluatedExpr
  File "/usr/lib/python3.12/site-packages/sympy/core/expr.py", line 4159, in <module>
    from .mul import Mul
  File "/usr/lib/python3.12/site-packages/sympy/core/mul.py", line 2193, in <module>
    from .numbers import Rational
  File "/usr/lib/python3.12/site-packages/sympy/core/numbers.py", line 4567, in <module>
    _sympy_converter[type(mpmath.rational.mpq(1, 2))] = sympify_mpmath_mpq
                          ^^^^^^^^^^^^^^^
AttributeError: module 'mpmath' has no attribute 'rational'
```
I tried 1.12 + 62455412 but that commit is not enough. Still getting 3 test failures in:
```
[...]
sympy/logic/tests/test_boolalg.py[82] ...E......................................
....f..................w................                                  [FAIL]
[...]
sympy/utilities/tests/test_pickling.py[43] ...EE......f..........ff..f........ff
X.....                                                                    [FAIL]
[...]
```
The details are:
```
________________________________________________________________________________
__________________ sympy/logic/tests/test_boolalg.py:test_Xor __________________
Traceback (most recent call last):
  File "/builddir/python3-sympy-1.12/sympy/logic/tests/test_boolalg.py", line 112, in test_Xor
    assert Xor(A < 1, A >= 1, B) == Xor(0, 1, B) == Xor(1, 0, B)            
           ^^^^^^^^^^^^^^^^^^^^^
  File "/builddir/python3-sympy-1.12/sympy/logic/boolalg.py", line 1015, in __new__
    odd = ~odd                                                              
          ^^^^
DeprecationWarning: Bitwise inversion '~' on bool is deprecated. This returns the bitwise inversion of the underlying int object and is usually not what you expect from negating a bool. Use the 'not' operator for boolean negation or ~int(x) if you really want the bitwise inversion of the underlying int.
________________________________________________________________________________
___________ sympy/utilities/tests/test_pickling.py:test_core_numbers ___________
Traceback (most recent call last):
  File "/builddir/python3-sympy-1.12/sympy/utilities/tests/test_pickling.py", line 113, in test_core_numbers
    check(c)
  File "/builddir/python3-sympy-1.12/sympy/utilities/tests/test_pickling.py", line 67, in check
    b = pickle.loads(pickle.dumps(a, protocol))
                     ^^^^^^^^^^^^^^^^^^^^^^^^^                              
  File "/builddir/python3-sympy-1.12/sympy/core/basic.py", line 187, in __reduce_ex__
    return super().__reduce_ex__(protocol)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/builddir/python3-sympy-1.12/sympy/core/numbers.py", line 1204, in __getnewargs_ex__
    return ((mlib.to_pickable(self._mpf_),), {'precision': self._prec})
             ^^^^^^^^^^^^^^^^
AttributeError: module 'mpmath.libmp' has no attribute 'to_pickable'
________________________________________________________________________________
_________ sympy/utilities/tests/test_pickling.py:test_core_float_copy __________
Traceback (most recent call last):
  File "/builddir/python3-sympy-1.12/sympy/utilities/tests/test_pickling.py", line 121, in test_core_float_copy
    check(y)  # does not raise TypeError ("argument is not an mpz")
    ^^^^^^^^
  File "/builddir/python3-sympy-1.12/sympy/utilities/tests/test_pickling.py", line 67, in check
    b = pickle.loads(pickle.dumps(a, protocol))
                     ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/builddir/python3-sympy-1.12/sympy/core/basic.py", line 187, in __reduce_ex__
    return super().__reduce_ex__(protocol)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/builddir/python3-sympy-1.12/sympy/core/numbers.py", line 1204, in __getnewargs_ex__
    return ((mlib.to_pickable(self._mpf_),), {'precision': self._prec})
             ^^^^^^^^^^^^^^^^
AttributeError: module 'mpmath.libmp' has no attribute 'to_pickable'
```

**Comment by tornaria** [comment]
The error in boolalg should be fixed by 2e09b42. But I couldn't find anything about `to_pickable`.

**Comment by tornaria** [comment]
Relevant: https://github.com/mpmath/mpmath/issues/440 and https://github.com/mpmath/mpmath/pull/667.

**Comment by oscarbenjamin** [comment]
SymPy 1.12.1 didn't get released. We're going for 1.13 now.
