### ISSUE TITLE
Test failure `TypeError: Basic.xreplace() missing 1 required positional argument: 'rule'`

### ISSUE THREAD

**Issue by oscarbenjamin** [sympy/sympy#23774]
Now that CPython 3.11.0b4 has rolled out in CI there is a nondetermistic test failure:
https://github.com/sympy/sympy/runs/7318381460?check_suite_focus=true
```
__________ sympy/core/tests/test_function.py:test_subs_in_derivative ___________
Traceback (most recent call last):
  File "/home/runner/work/sympy/sympy/sympy/core/tests/test_function.py", line 746, in test_subs_in_derivative
    assert (abstract.subs(f, F).doit() - concrete).simplify() == 0
            ^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/sympy/sympy/sympy/core/basic.py", line 997, in subs
    rv = rv._subs(old, new, **kwargs)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/sympy/sympy/sympy/core/cache.py", line 70, in wrapper
    retval = cfunc(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/sympy/sympy/sympy/core/basic.py", line 1111, in _subs
    rv = fallback(self, old, new)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/sympy/sympy/sympy/core/basic.py", line 1083, in fallback
    arg = arg._subs(old, new, **hints)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/sympy/sympy/sympy/core/cache.py", line 70, in wrapper
    retval = cfunc(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/sympy/sympy/sympy/core/basic.py", line 1111, in _subs
    rv = fallback(self, old, new)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/sympy/sympy/sympy/core/basic.py", line 1083, in fallback
    arg = arg._subs(old, new, **hints)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/sympy/sympy/sympy/core/cache.py", line 70, in wrapper
    retval = cfunc(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/sympy/sympy/sympy/core/basic.py", line 1109, in _subs
    rv = self._eval_subs(old, new)
         ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/sympy/sympy/sympy/core/function.py", line 2[366](https://github.com/sympy/sympy/runs/7318381460?check_suite_focus=true#step:16:367), in _eval_subs
    expr = self.expr._subs(old, new)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/sympy/sympy/sympy/core/cache.py", line 70, in wrapper
    retval = cfunc(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/sympy/sympy/sympy/core/basic.py", line 1109, in _subs
    rv = self._eval_subs(old, new)
         ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/sympy/sympy/sympy/core/function.py", line 1738, in _eval_subs
    ofree = old.xreplace(syms).free_symbols
            ^^^^^^^^^^^^^^^^^^
TypeError: Basic.xreplace() missing 1 required positional argument: 'rule'
```
I've come up with a minimal reproducer:
```python
from sympy import *

x, y = symbols('x, y')
f = Function('f')

# These two lines look irrelevant but are needed:
expr = sin(x*exp(y))
Derivative(expr, y).subs(y, x).doit()

expr = Subs(Derivative(f(f(x)), x), f, cos)

# This is where it blows up:
expr.doit()
```
Running that will sometimes fail:
```console
$ python bug.py 
$ python bug.py 
$ python bug.py 
$ python bug.py 
$ python bug.py 
Traceback (most recent call last):
  File "/home/oscar/current/sympy/sympy.git/bug.py", line 13, in <module>
    expr.doit()
    ^^^^^^^^^^^
  File "/home/oscar/current/sympy/sympy.git/sympy/core/function.py", line 2246, in doit
    e = e.subs(vi, p[i])
        ^^^^^^^^^^^^^^^^
  File "/home/oscar/current/sympy/sympy.git/sympy/core/basic.py", line 997, in subs
    rv = rv._subs(old, new, **kwargs)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/oscar/current/sympy/sympy.git/sympy/core/cache.py", line 70, in wrapper
    retval = cfunc(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/oscar/current/sympy/sympy.git/sympy/core/basic.py", line 1109, in _subs
    rv = self._eval_subs(old, new)
         ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/oscar/current/sympy/sympy.git/sympy/core/function.py", line 1737, in _eval_subs
    nfree = new.xreplace(syms).free_symbols
            ^^^^^^^^^^^^^^^^^^
TypeError: Basic.xreplace() missing 1 required positional argument: 'rule'
```
It can be made to fail deterministically with PYTHONHASHSEED:
```console
$ PYTHONHASHSEED=1 python bug.py 
Traceback (most recent call last):
  File "/home/oscar/current/sympy/sympy.git/bug.py", line 13, in <module>
    expr.doit()
    ^^^^^^^^^^^
  File "/home/oscar/current/sympy/sympy.git/sympy/core/function.py", line 2246, in doit
    e = e.subs(vi, p[i])
        ^^^^^^^^^^^^^^^^
  File "/home/oscar/current/sympy/sympy.git/sympy/core/basic.py", line 997, in subs
    rv = rv._subs(old, new, **kwargs)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/oscar/current/sympy/sympy.git/sympy/core/cache.py", line 70, in wrapper
    retval = cfunc(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/oscar/current/sympy/sympy.git/sympy/core/basic.py", line 1109, in _subs
    rv = self._eval_subs(old, new)
         ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/oscar/current/sympy/sympy.git/sympy/core/function.py", line 1737, in _eval_subs
    nfree = new.xreplace(syms).free_symbols
            ^^^^^^^^^^^^^^^^^^
TypeError: Basic.xreplace() missing 1 required positional argument: 'rule'
```
With that it also fails with CPython 3.11.0b3 so I this is not a new bug in 3.11.0b4. In fact I can reproduce it with 3.11.0a1 and have bisected it to https://github.com/python/cpython/commit/96346cb6d0593ef9ec122614347ccb053cd63433.

A sketch of the problem is this (although this does not reproduce it):
```python
class ManagedProperties(type):
    def __init__(cls, *args, **kws):
        pass

class Basic(metaclass=ManagedProperties):
    def xreplace(self, rule):
        print('Basic')

class Expr(Basic):
    pass

class FunctionClass(ManagedProperties):
    @property
    def xreplace(self):
        return lambda rule: print('functionclass')

class Application(Basic, metaclass=FunctionClass):
    pass

class Function(Application, Expr):
    pass

class cos(Function):
    pass

cos.xreplace(1)
```
Here `cos.xreplace` will give the lambda function returned by the FunctionClass property. However it seems that under certain conditions somehow triggered by the reproducer above and depending on the hash seed `cos.xreplace(1)` will end up calling `Basic.xreplace(1)` which fails because `Basic.xreplace` is an unbound method and needs to be called with a `self` argument.

I think this is a bug in CPython so I'll open a CPython issue.

**Comment by oscarbenjamin** [comment]
This is confirmed as a CPython bug: https://github.com/python/cpython/issues/94822#issuecomment-1183672753

**Comment by asmeurer** [comment]
If I'm reading that GitHub discussion properly, it sounds like there are some new performance optimizations in Python 3.11 which are going to be completely disabled if you use metaclasses.

**Comment by oscarbenjamin** [comment]
They might eventually go for a solution that doesn't disable metaclasses. I think right now they're looking for a quick regression free fix because they have a release blocker for 3.11.

In any case I think it's almost always a mistake to use metaclasses. It's probably stuff like that that results in SymPy being slower under PyPy as well.

The particular use of metaclasses here is to make this work:
```python
In [2]: sin.xreplace({sin:cos})
Out[2]: cos
```
In my opinion that should just fail because `sin` is not an *instance* of `Basic`. It would be better if it was an instance of `Basic` (#4787) but until then any attempt like this to make it sort of work with metaclasses is a bad idea.

**Comment by oscarbenjamin** [comment]
This is fixed in CPython 3.11.0b5
