### PR TITLE
init_session: improved detection of current IPython session

### PR DESCRIPTION
**Pull request by elvis-sik**
Previously, to detect if there was a running IPython session, init_session relied on a function called get_ipython, injected into the global namespace by IPython. However, this function is not in scope during initialization, particularly, it is not in scope during the execution of startup scripts. This had the unfortunate consequence of creating  new mainloop on top of the previous one when init_session was called in a startup script. This commit changes the detection to use IPython.terminal.interactiveshell.TerminalInteractiveShell.initialized, a public-API method that works in this edge case as expected. Hence, it
becomes possible to use init_session in startup scripts.

### CODE REVIEW

**Comment by elvis-sik** [comment]
This is a fix to this  #11419

**Comment by moorepants** [comment]
Have you tested it on various versions of IPython between 0.11 and the current release?

**Comment by elvis-sik** [comment]
I haven't. Would it be good enough if I tried it on one version for each major version? So, for the `1.x` series, I might just test for `1.2.1`, for example.

**Comment by moorepants** [comment]
Yes, please try it on some previous versions. Maybe the earliest supported in the code and another random one inbetween.

Is it possible to add a unit test for this fix?

**Comment by jksuom** [comment]
This is what I get with IPython v.0.12.1:
```
sympy pr-11426$ bin/isympy
Traceback (most recent call last):
  File "bin/isympy", line 357, in <module>
    main()
  File "bin/isympy", line 354, in main
    init_session(ipython, **args)
  File "/home/jks/test/sympy/sympy/interactive/session.py", line 420, in init_session
    tis = IPython.terminal.interactiveshell.TerminalInteractiveShell
AttributeError: 'module' object has no attribute 'terminal'
```
It seems that `get_ipython` was introduced in v.1.0.

**Comment by moorepants** [comment]
So, the code makes it think that if you use anything greater than 0.11 it will work. I don't think we need to support 0.11, but if you want to change the code so it works with 1.0+ that would be fine. You can raise an error if anything less than 1.0 is found.

**Comment by jksuom** [comment]
> You can raise an error if anything less than 1.0 is found.

I think that should not be done. Instead, the current code could be followed. It works fine with v.0.12.1 that I'm using.

**Comment by moorepants** [comment]
Well, it seems that there is an issue with the current code that prevents this from being used in startup scripts. How should that be addressed?

It is worth noting that IPython 0.11 was released 6 years ago. https://pypi.python.org/pypi/ipython/0.11

**Comment by moorepants** [comment]
Oh I see, @jksuom , just leave the old code path for 0.11 to 1.0. That's fine too.

**Comment by jksuom** [comment]
I am still using Ubuntu 12.04 that has v.0.12.1.

**Comment by moorepants** [comment]
We should probably have some kind guideline for what we support. I'm not sure supporting LTS versions of Ubuntu for their full lifetime is in SymPy's best interest, but maybe. 12.04 has less than a year left of official support. Shouldn't you be using 0.7.1 SymPy if you are using 0.12 IPython :)

File: sympy/interactive/session.py [hunk 1]
```diff
@@ -417,10 +417,10 @@ def init_session(ipython=None, pretty_print=True, order=None,
             ip = None
         else:
             if V(IPython.__version__) >= '0.11':
-                try:
-                    ip = get_ipython()
-                except NameError:
-                    ip = None
+                tis = IPython.terminal.interactiveshell.TerminalInteractiveShell
```
Comment (jksuom) [inline sympy/interactive/session.py]: Would it be possible to do something like this:
```
        try:
            from IPython import get_ipython
        except ImportError:
            ip = None
        else:
            ip = get_ipython()
```

**Comment by elvis-sik** [comment]
@jksuom it does not work here (IPython 5.0)

**Comment by jksuom** [comment]
What happens? ImportError?

**Comment by elvis-sik** [comment]
I guess I must have done something wrong. I opened the files, and I didn't find the edit with your suggestion. I corrected it, reinstalled, and re-tried, and it seems to be working.

I might try this on several IPython versions if this seems promising to you.

**Comment by elvis-sik** [comment]
I think this working makes sense as `get_ipython` is almost the same thing I was doing manually: [get_ipython source](https://github.com/ipython/ipython/blob/master/IPython/core/getipython.py). But it seems to be more portable...

**Comment by jksuom** [comment]
I've also noticed that the logic of your patch is almost the same as that of `get_ipython`. Neither method seems to deliver a shell if one was not already initialized. That is why I suggest that you try the following where the initialization test is omitted.
```
    try:
        from IPython.terminal.interactiveshell import TerminalInteractiveShell
    except ImportError:
        ip = None
    else:
        ip = TerminalInteractiveShell.instance()
```
That should work with old ipython versions (that raise `ImportError`) and, for newer versions, it should create an instance if that doesn't exist already. (I think this would be a minimal change.)

**Comment by elvis-sik** [comment]
I tested your suggestion on IPython 0.13.2, 1.2.1, 2.4 and 3.2.1 on Python 3.5.2. Version 0.13.2 does open a REPL which, upon being exitted, gets me to the IPython REPL which I was trying to get at in the first place. This happens even if I, being already on the IPython REPL, as opposed to during startup script loading-time, call `init_session`.

**Comment by jksuom** [comment]
> Version 0.13.2 does open a REPL which, upon being exitted, gets me to the IPython REPL which I was trying to get at in the first place. 

Is this the result of `init_session()` or `init_session('ipython')`?

**Comment by elvis-sik** [comment]
That was the result of `init_session()`. With `init_session('ipython')` I get still more weird behavior. I get into a REPL. Some exceptions occur, but I get into the REPL and I can type code. SymPy was imported correctly. Then if I try to quit (`C-d C-d`), it seems the startup script gets loaded again. And so I get into yet another REPL, with the same exceptions, and everything is the same.

I can go on, quitting REPLs indefinitely.

Don't you think we could have two separate behaviors, one for versions pre-1.0 and another for 1.0 and up (which could be exactly what we have at the moment)?

**Comment by jksuom** [comment]
I think the behaviour can be different for pre-1.0 versions in a startup script. BTW, have you tested `init_session` both with and without 'ipython'. How do they behave on IPython 1.0 and later? Is there any difference when using the old `init_session`?

**Comment by asmeurer** [comment]
@jksuom's way seems better if it works. You can also CC the IPython devs @Carreau @takluyver to see what they think. 

Regarding older versions, I think we should continue to support them for now, although for the non-latest version it's more important to just avoid regressions than to fix bugs or add new features, so if something didn't work before in an older version of IPython it isn't necessary to fix it.

**Comment by takluyver** [comment]
FWIW, I think `get_ipython()` should be visible in startup scripts, and I hope to fix IPython so that it is. Obviously that will leave older versions out there in which it's not, though.

**Comment by takluyver** [comment]
ipython/ipython#9818

**Comment by asmeurer** [comment]
Is there a good reason not to import it anyway?

**Comment by takluyver** [comment]
Importing it should be fine. Both imports under consideration should have been around for several versions, though I don't remember exactly when they became available.

**Comment by Carreau** [comment]
Thanks @takluyver for taking care of this, I'm way behind on my backlog this week, sorry to have been mostly silent.

**Comment by elvis-sik** [comment]
So @asmeurer, AFAICT what should be done is something like this:

```python
try:
    from IPython import get_ipython
except ImportError:
    try:
        ip = get_ipython()
    except NameError:
        ip = None
else:
    ip = get_ipython()
```

**Comment by jksuom** [comment]
I think one `try:` should be enough.

**Comment by asmeurer** [comment]
We'll need to check older versions of IPython, but my suggestion is to just do the import.

**Comment by elvis-sik** [comment]
I tried `0.13.2` and it turns out it doesn't export `get_ipython`. Maybe I should search for an analogous function in the docs?

**Comment by jksuom** [comment]
> I tried 0.13.2 and it turns out it doesn't export get_ipython.

It seems that such a function is not available in ipython < 1.0, and the initialization has to be done differently.

In those versions the import line will raise an ImportError. In that case one should set `ip = None` (with no second try resulting always in a NameError).
Then, if the argument `ipython` of `init_session` is not `None` or `False`,  the control will pass to [this line](https://github.com/sympy/sympy/blob/master/sympy/interactive/session.py#L437) that will do the proper initialization.

So, nothing more is needed for those older versions. Setting `ip = None` after `ImportError` and `ipython` not `None` or `False` should suffice.

**Comment by elvis-sik** [comment]
With this commit I am getting `init_session` to work with IPython 0.13 on startup scripts. But I get a `WARNING: help() not available - check site.py` on initialization and exit of IPython.

**Comment by elvis-sik** [comment]
This is the place:

https://github.com/ipython/ipython/blob/0.13.x/IPython/core/interactiveshell.py#L1114

File: sympy/interactive/session.py [hunk 2]
```diff
@@ -416,11 +416,12 @@ def init_session(ipython=None, pretty_print=True, order=None,
...
             ip = None
         else:
-            if V(IPython.__version__) >= '0.11':
-                try:
-                    ip = get_ipython()
-                except NameError:
-                    ip = None
+            version = V(IPython.__version__)
+            if '1.0' > version >= '0.11':
+                ip = IPython.core.ipapi.get()
```
Comment (jksuom) [inline sympy/interactive/session.py]: The docstring of ipapi says:
> This module is *completely* deprecated and should no longer be used for
any purpose.

Instead of this, it would probably suffice to add `from IPython import get_ipython` after `try:` above and then change `NameError` to `ImportError`.

**Comment by jksuom** [comment]
This seems to work on IPython v.0.12.1. +1

**Comment by elvis-sik** [comment]
It does work on IPython 5.0, which I am using.

**Comment by jksuom** [comment]
Thanks, merging.
