### ISSUE TITLE
AttributeError in printing/pycode.py from lambdify

### ISSUE THREAD

**Issue by jsharkey13** [sympy/sympy#19168]
I was trying to update from SymPy `1.4` to `1.5.1`, but my module's automated tests discovered a problem in SymPy. Unevaluated Pow objects containing integers cannot be passed into `lambdify` due to an `AttributeError` in `printing/pycode.py`.

If `evaluate=False` is not provided, then SymPy simplifies the expression down to `Rational(1, 3)` automatically, which has no such issue in `lambdify`. Unfortunately `evaluate=False` is critical for the AST expression equality checking I need to do.

This error occurs in `1.5` and `1.5.1`, but in `1.4` it behaves as expected. I narrowed down our complex test case to the trivial example below, which ought to output `0.5` as it does in `1.4`:
```
>>> from sympy import Integer, Pow, lambdify
>>> e = Pow(Integer(2), Integer(-1), evaluate=False)
>>> lambdify([], e, "numpy")()

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/site-packages/sympy/utilities/lambdify.py", line 777, in lambdify
    funcstr = funcprinter.doprint(funcname, args, expr)
  File "/usr/local/lib/python3.7/site-packages/sympy/utilities/lambdify.py", line 1026, in doprint
    funcbody.append('return ({})'.format(self._exprrepr(expr)))
  File "/usr/local/lib/python3.7/site-packages/sympy/printing/codeprinter.py", line 108, in doprint
    lines = self._print(expr).splitlines()
  File "/usr/local/lib/python3.7/site-packages/sympy/printing/printer.py", line 287, in _print
    return getattr(self, printmethod)(expr, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/sympy/printing/pycode.py", line 715, in _print_Pow
    return self._hprint_Pow(expr, rational=rational, sqrt='numpy.sqrt')
  File "/usr/local/lib/python3.7/site-packages/sympy/printing/pycode.py", line 423, in _hprint_Pow
    if expr.exp == S.Half and not rational:
AttributeError: 'Float' object has no attribute 'exp'
```

This example is the simplest possible case that reproduces the issue; usually there are an arbitrary number of free symbols determined at runtime (hence my use of `lambdify` and not `evalf`). Note that the error is on a `Float` object, which seems odd since there are only `Pow` and `Integer` objects initially; I don't know how the `Float` comes in, nor how it ends up in `_print_Pow`.

[A quick `git blame`](https://github.com/sympy/sympy/blame/sympy-1.5/sympy/printing/pycode.py#L423) suggests that the bug might have been introduced in #16901 when the `_hprint_Pow` function was introduced. But a `Float` inside `_print_Pow` may be caused by something more serious?
