### ISSUE TITLE
mypy job in CI failing with mypy 1.1.1

### ISSUE THREAD

**Issue by brocksam** [sympy/sympy#24873]
The mypy CI job is now installing mypy 1.1.1 (previously was mypy 1.0.1), which appears to be flagging one error and one warning. Outputs from a mypy job are:

```
sympy/parsing/sympy_parser.py:1075: error: Incompatible types in assignment (expression has type "CodeType", variable has type "str")  [assignment]
sympy/ntheory/tests/test_qs.py:65: note: By default the bodies of untyped functions are not checked, consider using --check-untyped-defs  [annotation-unchecked]
```

**Comment by sylee957** [comment]
The last merge commit that failed is from 5c03f65eeab34368bec9a7f76feffaf2f0b7a110
I notice the version of mypy had been updated to `1.1.1` from `1.0.1`, so some changes in mypy can be related

**Comment by sylee957** [comment]
There are other mypy tests failing
```
sympy/parsing/sympy_parser.py:1075: error: Incompatible types in assignment (expression has type "CodeType", variable has type "str")  [assignment]
sympy/ntheory/tests/test_qs.py:65: note: By default the bodies of untyped functions are not checked, consider using --check-untyped-defs  [annotation-unchecked]
```

**Comment by oscarbenjamin** [comment]
The failure is:
```
sympy/core/tests/test_symbol.py:402: error: Cannot find implementation or library stub for module named "pyodide_js"  [import]
sympy/core/tests/test_symbol.py:402: note: See https://mypy.readthedocs.io/en/stable/running_mypy.html#missing-imports
Found 1 error in 1 file (checked 1430 source files)
```
That comes from gh-24882
