### ISSUE TITLE
Physics Dyadics do not render in LaTeX if contained in a sequence (tuple, list, etc)

### ISSUE THREAD

**Issue by moorepants** [sympy/sympy#13570]
```
d = Dyadic(...)
latex((d, d))
```

will not output correct latex for rendering in the notebook, etc.

**Comment by yashkgp** [comment]
Can I work on this issue?

**Comment by moorepants** [comment]
Yes, you are welcome to work on the issue.

**Comment by yashkgp** [comment]
Hey @moorepants ,
Should I start by making a test case? It would  great if you can guide me on this issue .

**Comment by moorepants** [comment]
Yes, starting by writing a test case is a great idea. Look in the physics vector printing code for the tests.

**Comment by yashkgp** [comment]
Hey @moorepants, In the documentation, its recommended that the `dyadic` class should be only called when you have to initiate a zero dyadic object.(Just like vectors)Something like this : 
```
d=Dyadic(0)
```
In all other instances when Dyadic object is printed, it is returned by a function (like inertia, outer)
So I think a directly calling Dyadic class through a sequence would give wrong results in printing. Correct me if I am wrong.

**Comment by moorepants** [comment]
You should construct the Dyadic from ReferenceFrame unit vectors not as I specified above. This will allow you to check the printing.

For example:

```python
A = ReferenceFrame('A')
A.x.outer(A.y)
```

**Comment by yashkgp** [comment]
Hey @moorepants Could you tell what do you mean by Dyadic contained in a sequence 
I have tried something like this
```python
from sympy import symbols
from sympy.physics.vector import ReferenceFrame,vlatex,outer
N = ReferenceFrame('N')
a=[N.x.outer(N.y),N.x.outer(N.z)]
print (vlatex(a[0]))
```
Its printing 
```
\mathbf{\hat{n}_x}\otimes \mathbf{\hat{n}_z}
````
which I think is the correct representation 
It would be great if you can help me out .

**Comment by yashkgp** [comment]
@moorepants  What do you mean by Dyadic contained in list ?

**Comment by moorepants** [comment]
Yes, I believe so.

**Comment by oscargus** [comment]
I tried this in current master
```
from sympy.vector import BaseDyadic, CoordSys3D
A = CoordSys3D('A')
bd1 = BaseDyadic(A.i, A.j)
bd2 = BaseDyadic(A.j, A.i)
latex((bd1+bd2, bd1, bd2))
```
and got
`\left( (\mathbf{\hat{i}_{A}}{|}\mathbf{\hat{j}_{A}}) + (\mathbf{\hat{j}_{A}}{|}\mathbf{\hat{i}_{A}}), \  (\mathbf{\hat{i}_{A}}{|}\mathbf{\hat{j}_{A}}), \  (\mathbf{\hat{j}_{A}}{|}\mathbf{\hat{i}_{A}})\right)`

So either it is working now or we need a (non) working example to solve it.

**Comment by oscargus** [comment]
The following:
```
from IPython.display import display, Math
display(Math(r'\left( (\mathbf{\hat{i}_{A}}{|}\mathbf{\hat{j}_{A}}) + (\mathbf{\hat{j}_{A}}{|}\mathbf{\hat{i}_{A}}), \  (\mathbf{\hat{i}_{A}}{|}\mathbf{\hat{j}_{A}}), \  (\mathbf{\hat{j}_{A}}{|}\mathbf{\hat{i}_{A}})\right)'))
```

Gives:
![image](https://user-images.githubusercontent.com/8114497/52734771-4dfd8080-2fc6-11e9-9f05-8713e53fdf78.png)
so it seems like the LaTeX is correct. Not obvious why it is not rendering, but I re-label this to IPython.

**Comment by oscargus** [comment]
It is obvious why it is not rendering in my comment above...

From the release notes:
"SymPy objects now render as LaTeX automatically in the Jupyter notebook. init_printing() is still required to make Python builtin numeric types (such as int and float) render as LaTeX, Python container types (such as list and dict) containing SymPy objects render as LaTeX, to change the printer settings, or to get LaTeX printing in the qtconsole. (#15368 by @asmeurer)"

Still, this issue is from before that.

**Comment by moorepants** [comment]
In Jupyter I get this error:

```
sympy.init_printing()
from sympy import symbols
from sympy.physics.vector import ReferenceFrame,vlatex,outer
N = ReferenceFrame('N')
a=[N.x.outer(N.y),N.x.outer(N.z)]
a
```

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
/opt/conda/lib/python3.6/site-packages/IPython/core/formatters.py in __call__(self, obj)
    700                 type_pprinters=self.type_printers,
    701                 deferred_pprinters=self.deferred_printers)
--> 702             printer.pretty(obj)
    703             printer.flush()
    704             return stream.getvalue()

/opt/conda/lib/python3.6/site-packages/IPython/lib/pretty.py in pretty(self, obj)
    383                 if cls in self.type_pprinters:
    384                     # printer registered in self.type_pprinters
--> 385                     return self.type_pprinters[cls](obj, self, cycle)
    386                 else:
    387                     # deferred printer

/opt/conda/lib/python3.6/site-packages/sympy/interactive/printing.py in _print_plain(arg, p, cycle)
     66         """caller for pretty, for use in IPython 0.11"""
     67         if _can_print_latex(arg):
---> 68             p.text(stringify_func(arg))
     69         else:
     70             p.text(IPython.lib.pretty.pretty(arg))

/opt/conda/lib/python3.6/site-packages/sympy/printing/pretty/pretty.py in pretty(expr, **settings)
   2339 
   2340     try:
-> 2341         return pp.doprint(expr)
   2342     finally:
   2343         pretty_use_unicode(uflag)

/opt/conda/lib/python3.6/site-packages/sympy/printing/pretty/pretty.py in doprint(self, expr)
     60 
     61     def doprint(self, expr):
---> 62         return self._print(expr).render(**self._settings)
     63 
     64     # empty op so _print(stringPict) returns the same

/opt/conda/lib/python3.6/site-packages/sympy/printing/printer.py in _print(self, expr, **kwargs)
    285                 printmethod = '_print_' + cls.__name__
    286                 if hasattr(self, printmethod):
--> 287                     return getattr(self, printmethod)(expr, **kwargs)
    288             # Unknown object, fall back to the emptyPrinter.
    289             return self.emptyPrinter(expr)

/opt/conda/lib/python3.6/site-packages/sympy/printing/pretty/pretty.py in _print_list(self, l)
   1907 
   1908     def _print_list(self, l):
-> 1909         return self._print_seq(l, '[', ']')
   1910 
   1911     def _print_tuple(self, t):

/opt/conda/lib/python3.6/site-packages/sympy/printing/pretty/pretty.py in _print_seq(self, seq, left, right, delimiter, parenthesize)
   1882                 s = pform
   1883             else:
-> 1884                 s = prettyForm(*stringPict.next(s, delimiter))
   1885                 s = prettyForm(*stringPict.next(s, pform))
   1886 

/opt/conda/lib/python3.6/site-packages/sympy/printing/pretty/stringpict.py in next(*args)
     70         newHeightBelowBaseline = max(
     71             obj.height() - obj.baseline
---> 72             for obj in objects)
     73         newHeight = newBaseline + newHeightBelowBaseline
     74 

/opt/conda/lib/python3.6/site-packages/sympy/printing/pretty/stringpict.py in <genexpr>(.0)
     70         newHeightBelowBaseline = max(
     71             obj.height() - obj.baseline
---> 72             for obj in objects)
     73         newHeight = newBaseline + newHeightBelowBaseline
     74 

AttributeError: 'Fake' object has no attribute 'height'
```

The object still renders below, but throws this error. I used `sympy.init_printing()`.

**Comment by oscargus** [comment]
Thanks!
I think it is because for some reason both the pretty and LaTeX versions are generated, although only the LaTeX one is shown. I noticed that while fixing another issue with the LaTeX printer, while fixing it, I still got exceptions from the pretty printer. Not sure if it is a fallback or if there is something in `init_printing` taking on a weird state (most options are True/False, so I do not know if one can turn on both somehow).

Either way, it is convenient if it doesn't happen and that one can print this in the pretty printer (which I assume is not possible at the moment).

**Comment by moorepants** [comment]
Yes it is. The jupyter stuff calls three or more printers on every printed statement.

**Comment by oscargus** [comment]
Just briefly browsing the code, I guess the `Fake` class in Dyadic.py should have a height method (or inherit from something in Pretty).

**Comment by arooshiverma** [comment]
Can I work on this one?

**Comment by moorepants** [comment]
This works in JupyterLab + SymPy 1.4 if you call `init_printing`:
![Selection_587](https://user-images.githubusercontent.com/276007/66497929-14581900-ea72-11e9-9927-7202e0c8ad52.png)

**Comment by moorepants** [comment]
The example that errored before:
```
sympy.init_printing()
from sympy import symbols
from sympy.physics.vector import ReferenceFrame,vlatex,outer
N = ReferenceFrame('N')
a=[N.x.outer(N.y),N.x.outer(N.z)]
a
```
also works if init printing is called. Going to close this.
