### PR TITLE
Add safe flag to sympify()

### LINKED ISSUE #10805: Safety
I think `sympy` shoudl be made safer for untrusted input, as discussed in the comments on [this stackoverflow issue](http://stackoverflow.com/q/35929640/4414003). Since `sympy` uses `eval` under the hood, it's vulnerable to attacks. There's really no reason to allow attribute access, etc, which leads to vulnerabilities like [these](http://nedbatchelder.com/blog/201206/eval_really_is_dangerous.html). I'd love a safer sympy that I could really use with foreign input.

### PR DESCRIPTION
**Pull request by asmeurer**
True (the default) causes it to raise UnsafeSympifyError on strings with AST elements that aren't in a whitelist (in particular, things like attribute access, comprehensions, and f-strings are not allowed). It also does a filter on the namespace to disallow names that might be used to bypass it, including `sympify` itself. See the added notes in the `sympify` docstring for more information. 

This requires several str printers that used `.` to be changed, so that they can still be round-tripped with `sympify`. The one that I haven't changed yet is new assumptions predicates, like `Q.positive`, as I'm not sure how I feel about it. Maybe we should only require the `srepr` printer to be fully compatible with safe sympify? 

**Example**

```py
>>> sympify('a.b')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "./sympy/core/sympify.py", line 434, in sympify
    transformations=transformations, evaluate=evaluate, safe=safe)
  File "./sympy/parsing/sympy_parser.py", line 954, in parse_expr
    code = stringify_expr(s, local_dict, global_dict, transformations, safe=safe)
  File "./sympy/parsing/sympy_parser.py", line 856, in stringify_expr
    check_string_for_safety(res)
  File "./sympy/parsing/safe_parser.py", line 134, in check_string_for_safety
    raise UnsafeSympifyError(s, reason='Non-whitelisted AST node %s found' % node)
sympy.core.sympify.UnsafeSympifyError: "Symbol ('a' ).b " cannot be parsed safely. Reason: Non-whitelisted AST node <_ast.Attribute object at 0x11fa2a198> found.
>>> sympify('sympify("a.b", safe=False)')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "./sympy/core/sympify.py", line 434, in sympify
    transformations=transformations, evaluate=evaluate, safe=safe)
  File "./sympy/parsing/sympy_parser.py", line 954, in parse_expr
    code = stringify_expr(s, local_dict, global_dict, transformations, safe=safe)
  File "./sympy/parsing/sympy_parser.py", line 856, in stringify_expr
    check_string_for_safety(res)
  File "./sympy/parsing/safe_parser.py", line 139, in check_string_for_safety
    raise UnsafeSympifyError(s, reason='disallowed name %r found' % node.id)
sympy.core.sympify.UnsafeSympifyError: 'sympify ("a.b",safe =False )' cannot be parsed safely. Reason: disallowed name 'sympify' found.
```

Fixes #10805.

### CODE REVIEW

**Comment by asmeurer** [comment]
I have no idea if the tests will pass. 

Still TODO: 
- [ ] tests for `safe`
- [ ] a hook to make sure that no part of SymPy itself uses `safe=False` (as that would defeat the purpose).

**Comment by asmeurer** [comment]
And there's another issue:

```py
>>> sympify('sympify("a.name", safe=False)')
'a'
```

And this also works

```
>>> e = eval
>>> sympify('e("x.name")', locals=locals())
'x'
```

So now I'm unsure about the whole thing actually. 😞

**Comment by asmeurer** [comment]
I suppose we could hide `eval`, `exec`, and `sympify` (others?) from the default locals dict, and if someone passes their own, it is up to them to ensure that it is safe.

**Comment by asmeurer** [comment]
We also have to disable comprehensions (they create their own namespace). I think we are fine with lambdas because we parse them into Lambdas anyway, but I'll need to check.

**Comment by asmeurer** [comment]
It seems like it is already working, actually, because both `eval` and `exec` get transformed to `Symbol('eval')` and `Symbol('exec')`. That's in Python 3. In Python 2, `exec` is a keyword and cannot be part of an expression. 

I want to hammer on this some more, and it would be great it someone else could look at it as well, but I think this is safe, so long as you do not pass in a locals dict. If you do, you have to be careful that no one has snuck in a way to call `eval` in it. 

We should also audit our use of `eval` and `exec` in the code to make sure there aren't other ways to sneak in arbitrary code execution.

**Comment by asmeurer** [comment]
OK, eval and exec are find, but sympify is more problematic:

```
>>> sympify('[sympify("[I for I in ().__class__.__base__.__subclasses__() if I.__name__ == \'catch_warnings\'][0]()._module.__builtins__[\'print\'](\'hello\')", safe=False) for Sum in Range(1)]', {'sympify': None})
hello
```

Note that I have to use variable names in the comprehensions that are SymPy names, as otherwise it tries to wrap them in Symbol. 

So I think we should

- Block the name `sympify` in the parser.
- Disable comprehensions. 

The latter is unfortunate, as it means we have to parse an AST for the string as well as tokenizing it, which could affect performance (I don't know how important performance is for sympify of strings).

**Comment by asmeurer** [comment]
Now things like `S.Reals` print as `"S.Reals"`. So we should somehow whitelist singletonized classes on the `S` object. Or maybe we should make all singletonized objects accessible without `S`.

**Comment by asmeurer** [comment]
https://github.com/sympy/sympy/issues/4862 concerns updating the tokenizer to support Python 3. We should probably fix that issue before finishing this PR.

**Comment by asmeurer** [comment]
I've been working on this. I have a working AST node whitelist implementation. Any reviews would be appreciated. 

The bad news here is that for str/srepr to stay compatible with sympify(), nothing can print using an attribute lookup. This means

- No `Q.real`. I'm thinking of making `Q('real')` work as a workaround.
- No `S.true` and so on. This is easy to fix: just print these as the name (`true`). All singleton names ought to be imported anyway.
- No `X.T` for Transpose. We can just print `Transpose(X)` and leave the `T` to the pretty printer.
- No `Interval.open`/`Interval.Ropen`/`Interval.Lopen` (in the printers). I've changed these to print like `Interval(0, 1, left_open=True, right_open=True)`, and so on. It's a bit more verbose for some doctests. 

I'm still working on some of the above items, but reviews are welcome, particularly on the safe parsing parts. I've written up what I see as the caveats in the sympify docstring. I'm sorry if the diff is out of control because of the printer changes. I mainly want reviews for the changes to the core. 

I've also made it so that calling `safe=False` raises an exception if it is done from SymPy library code. Otherwise, someone could use whatever library function does this to work around the safe parsing. I hope that's not a placebo (library code could still be using `eval` or `exec`). The idea is [defense in depth](https://en.wikipedia.org/wiki/Defense_in_depth_(computing)), in this case, defense against someone adding insecure code to SymPy.

**Comment by asmeurer** [comment]
We could also modify only the srepr printer for attribute access (though I think the `S.` should be removed from the str printer regardless). Then the `str` output wouldn't strictly be sympifable with safe=False under all circumstances, but srepr would be. 

What do people think? The `Q.real` thing bugs me a little bit that we'd have to change it. 

Another option is whitelisting attributes on certain objects, but I'm hesitant to do that as it opens the attack surface.

**Comment by asmeurer** [comment]
I'm not sure what should be done about this. I'd like to get it in the next release, but given the sensitive nature of the code, I don't feel comfortable merging it without a good review, preferably from someone who has a background in security. 

If we don't merge this for the 1.2 release, some of the commits should be backported (like the changes to `__init__.py`).

**Comment by asmeurer** [comment]
CC @scopatz can you take a look?

**Comment by oscarbenjamin** [comment]
I think it's a mistake to try either a whitelist or a blacklist. I don't even see the benefit of having a safe flag since we just shouldn't use eval at all. There is ast.literal_eval for parsing elementary Python types and containers which is explicitly intended to be safe.

Also sympify shouldn't parse strings at all or we should stop using it everywhere internally at least.

**Comment by asmeurer** [comment]
`ast.literal_eval` effectively uses a node whitelist, although it evaluates directly instead of using `eval`. 

Changing sympify to not use eval at all would be good, but a lot more work than this. It also wouldn't really solve the problem unless we whitelisted nodes. For instance, attributes would be just as dangerous with `getattr` calls.

Making sympify not accept strings is probably too big of a change to ever do. We should try to make the library code use `_sympify` wherever possible. Also this PR forces the use of `safe=True` in calls to `sympify` from library code.

**Comment by oscarbenjamin** [comment]
> `ast.literal_eval` effectively uses a node whitelist, although it evaluates directly instead of using `eval`.

The difference is that `literaleval` is specifically designed and documented to be safe for untrusted inputs and is better maintained/audited than anything here.

I think that getattr just shouldn't be allowed in sympify. If there are some reasonable expressions that involve attributes then they should be predefined somehow so that there is no actual call to getattr in response to string input.

**Comment by asmeurer** [comment]
I'm confused. Are you for or against this pull request? If you're against it, how do you propose to disallow getattrs in sympify?

**Comment by oscarbenjamin** [comment]
I think that this PR represents an improvement to the safeness of sympify/parse_expr. I also think that the changes like `S.Integers -> Integers` are an improvement.

Ultimately a different approach is needed though if we want to claim being able to safely support untrusted input. I am sure that someone malicious would be able to circumvent what we have here so I would still describe this as unsafe rather than "mostly safe".

**Comment by oscarbenjamin** [comment]
I would support merging this if it was mergeable.

**Comment by asmeurer** [comment]
I can look at fixing the merge conflicts. 

What other approach do you think is needed? Do you think it's better to write a direct evaluator to replace `eval`, or did you have something else in mind?

**Comment by oscarbenjamin** [comment]
Yes I think that a direct evaluator is needed with clear rules about what is or is not allowed in building an expression.

**Comment by asmeurer** [comment]
An ast whitelist is effectively this. 

But I suppose with a direct evaluator we can make rules that aren't just based on ast nodes. For instance, we could make rules that disallow numeric evaluation that produces large numbers that produce memory errors, like `10**10**100`. It would also allow us to use attribute syntax for certain things, because we could whitelist the attribute names (so stuff like `Q.real` would still work).

My biggest concerns here are:

1. Will disabling attribute access be a big issue for users? (see https://github.com/sympy/sympy/pull/12524#issuecomment-392654737)

2. Is doing a safe flag even a good idea in the first place? Or will it just be "security theater" that leads users into a false sense of security, because it can still be bypassed. Note that I don't currently know of any ways it can be bypassed, other than memory error things, but I also wouldn't be surprised if there is some way nonetheless.

**Comment by oscarbenjamin** [comment]
For `Q.real` we can enumerate the possible attributes that Q has and add them to the evaluator's namespace so effectively `Q.real` is a single token. I guess some things like `x.T` could be special cased (`parse_expr` could translate it to `Transpose(x)` before attempting any evaluation.

If the intention is to change sympify and str while keeping them consistent then sympify will have to continue to be more permissive for a while for backwards compatibility so users can still copy/paste expressions from other places. So I guess arbitrary attribute access from sympify should be deprecated (with a warning).

**Comment by oscarbenjamin** [comment]
@asmeurer will this be finished before 1.5?

**Comment by oscarbenjamin** [comment]
I just noticed that the milestone has already been pushed back to 1.6

**Comment by czgdp1807** [comment]
```python
>>> sympify('a.b')
Traceback (most recent call last):
  File "/usr/lib/python3.6/code.py", line 91, in runcode
    exec(code, self.locals)
  File "<console>", line 1, in <module>
  File "/home/czgdp1807/sympy_project/sympy/sympy/core/sympify.py", line 381, in sympify
    expr = parse_expr(a, local_dict=locals, transformations=transformations, evaluate=evaluate)
  File "/home/czgdp1807/sympy_project/sympy/sympy/parsing/sympy_parser.py", line 1008, in parse_expr
    return eval_expr(code, local_dict, global_dict)
  File "/home/czgdp1807/sympy_project/sympy/sympy/parsing/sympy_parser.py", line 903, in eval_expr
    code, global_dict, local_dict)  # take local objects in preference
  File "<string>", line 1, in <module>
AttributeError: 'Symbol' object has no attribute 'b'
>>> sympify('sympify("a.b", safe=False)')
Traceback (most recent call last):
  File "/usr/lib/python3.6/code.py", line 91, in runcode
    exec(code, self.locals)
  File "<console>", line 1, in <module>
  File "/home/czgdp1807/sympy_project/sympy/sympy/core/sympify.py", line 381, in sympify
    expr = parse_expr(a, local_dict=locals, transformations=transformations, evaluate=evaluate)
  File "/home/czgdp1807/sympy_project/sympy/sympy/parsing/sympy_parser.py", line 1008, in parse_expr
    return eval_expr(code, local_dict, global_dict)
  File "/home/czgdp1807/sympy_project/sympy/sympy/parsing/sympy_parser.py", line 903, in eval_expr
    code, global_dict, local_dict)  # take local objects in preference
  File "<string>", line 1, in <module>
TypeError: sympify() got an unexpected keyword argument 'safe'
```
The errors thrown are no longer the same. @asmeurer Any updates on the PR? Is there still a use case of `safe` argument?

**Comment by asmeurer** [comment]
Is that in this branch?

**Comment by asmeurer** [comment]
I don't intend to work on this for the 1.6 release. I think we should remove it from the release milestones.

**Comment by oscarbenjamin** [comment]
I agree. I've removed the milestone.

Fixing this properly so that eval is not used would be quite involved. Maybe we should put up a GSOC idea for completely rewriting `parse_expr` and some easy to fix ideas for cleaning up use of `sympify` around the codebase.

**Comment by asmeurer** [comment]
I think the idea here is solid. My biggest concern is that I'd like to see it reviewed by someone who has a better feel for this sort of thing, since it's kind of a "security fix".

The other idea is to walk the AST and construct an expression manually. I think that isn't difficult. We just need to write an ast node visitor that works for each of the classes. That could actually simplify some things a bit, because some of the transformations that we currently do at the tokenization level would be simpler at the ast level, like making undefined variables into Functions only when they are called. The basic idea of this is already implemented in the `EvaluateFalseTransformer` in sympy.parsing.sympy_parser. Doing it this way could also simplify the `sympify(evaluate=False)` flag, since we could run evaluate=False through the entire expression, not just the handful of nodes currently handled by `EvaluateFalseTransformer`. The end result would be more or less equivalent to what we have in this branch, since a blacklist of nodes would be implemented simply by not having them in the transformer class. For attribute lookups, we would either have to still completely disallow them as here, or else whitelist lookups that are known to be OK (the former is the safest).

One issue is that if we don't allow a `safe=False`, we would have a break of backwards compatibility. Some things that currently work, like list comprehension, wouldn't really be a big deal to remove, but disallowing any attribute lookups would be a problem. If we do allow some kind of `safe=False`, we will have to implement the same kinds of safeguards I have implemented here to ensure that it can't be trivially bypassed.

**Comment by czgdp1807** [comment]
Error thrown in master branch,
```python
>>> sympify('a.b')
Traceback (most recent call last):
  File "/usr/lib/python3.6/code.py", line 91, in runcode
    exec(code, self.locals)
  File "<console>", line 1, in <module>
  File "/home/czgdp1807ssd/sympy_project/sympy/sympy/core/sympify.py", line 406, in sympify
    expr = parse_expr(a, local_dict=locals, transformations=transformations, evaluate=evaluate)
  File "/home/czgdp1807ssd/sympy_project/sympy/sympy/parsing/sympy_parser.py", line 1008, in parse_expr
    return eval_expr(code, local_dict, global_dict)
  File "/home/czgdp1807ssd/sympy_project/sympy/sympy/parsing/sympy_parser.py", line 903, in eval_expr
    code, global_dict, local_dict)  # take local objects in preference
  File "<string>", line 1, in <module>
AttributeError: 'Symbol' object has no attribute 'b'
```
