### ISSUE TITLE
MatrixSymbol fails with 'matches'

### ISSUE THREAD

**Issue by jna29** [sympy/sympy#11948]
When calling `Basic.matches` with a `MatrixSymbol`, the method fails as such:

`AttributeError: 'str' object has no attribute 'xreplace'`

This is because in `Basic.matches`(sympy/core/basic) on line 1447 we call `self.args` in `for arg, other_arg in zip(self.args, expr.args):` which returns a tuple of type `(str, Symbol, Symbol)`. I'm guessing that the method isn't supposed to work with these types and so there might be an error in the logic.

Any suggestions for this fix? (I can work on it if necessary)

**Comment by asmeurer** [comment]
This works in master.

```py
>>> A = MatrixSymbol('A', 3, 3)
>>> a = Wild('a')
>>> a.matches(A)
{a_: A}
>>> A.match(a)
{a_: A}
```

So a test should be added for it. 

I also tested and it worked in SymPy 1.0 and 1.1, so maybe this wasn't the exact issue. At any rate, the problem as described here should be solved once https://github.com/sympy/sympy/pull/15121 is merged, if it still does exist.
