### ISSUE TITLE
test_theanocode failing on travis

### ISSUE THREAD

**Issue by sylee957** [sympy/sympy#15784]
I think test_theanocode had started failing on recent pull requests

For my PR #15722, and also all the other recent PRs made by others #15775, #15779, #15780

cf #15147
```
________________________________________________________________________________
_____ sympy/printing/tests/test_theanocode.py:test_theano_function_simple ______
Traceback (most recent call last):
  File "/home/travis/miniconda/envs/test-environment/lib/python2.7/site-packages/sympy-1.4.dev0-py2.7.egg/sympy/utilities/runtests.py", line 1306, in _timeout
    function()
  File "/home/travis/miniconda/envs/test-environment/lib/python2.7/site-packages/sympy-1.4.dev0-py2.7.egg/sympy/printing/tests/test_theanocode.py", line 277, in test_theano_function_simple
    f = theano_function_([x, y], [x+y])
  File "/home/travis/miniconda/envs/test-environment/lib/python2.7/site-packages/sympy-1.4.dev0-py2.7.egg/sympy/printing/tests/test_theanocode.py", line 54, in theano_function_
    return theano_function(inputs, outputs, **kwargs)
  File "/home/travis/miniconda/envs/test-environment/lib/python2.7/site-packages/sympy-1.4.dev0-py2.7.egg/sympy/printing/theanocode.py", line 500, in theano_function
    func = theano.function(tinputs, toutputs, **kwargs)
  File "/home/travis/miniconda/envs/test-environment/lib/python2.7/site-packages/theano/compile/function.py", line 317, in function
    output_keys=output_keys)
  File "/home/travis/miniconda/envs/test-environment/lib/python2.7/site-packages/theano/compile/pfunc.py", line 486, in pfunc
    output_keys=output_keys)
  File "/home/travis/miniconda/envs/test-environment/lib/python2.7/site-packages/theano/compile/function_module.py", line 1841, in orig_function
    fn = m.create(defaults)
  File "/home/travis/miniconda/envs/test-environment/lib/python2.7/site-packages/theano/compile/function_module.py", line 1715, in create
    input_storage=input_storage_lists, storage_map=storage_map)
  File "/home/travis/miniconda/envs/test-environment/lib/python2.7/site-packages/theano/gof/link.py", line 699, in make_thunk
    storage_map=storage_map)[:3]
  File "/home/travis/miniconda/envs/test-environment/lib/python2.7/site-packages/theano/gof/vm.py", line 1091, in make_all
    impl=impl))
  File "/home/travis/miniconda/envs/test-environment/lib/python2.7/site-packages/theano/gof/op.py", line 955, in make_thunk
    no_recycling)
  File "/home/travis/miniconda/envs/test-environment/lib/python2.7/site-packages/theano/gof/op.py", line 858, in make_c_thunk
    output_storage=node_output_storage)
  File "/home/travis/miniconda/envs/test-environment/lib/python2.7/site-packages/theano/gof/cc.py", line 1217, in make_thunk
    keep_lock=keep_lock)
  File "/home/travis/miniconda/envs/test-environment/lib/python2.7/site-packages/theano/gof/cc.py", line 1157, in __compile__
    keep_lock=keep_lock)
  File "/home/travis/miniconda/envs/test-environment/lib/python2.7/site-packages/theano/gof/cc.py", line 1609, in cthunk_factory
    key = self.cmodule_key()
  File "/home/travis/miniconda/envs/test-environment/lib/python2.7/site-packages/theano/gof/cc.py", line 1300, in cmodule_key
    c_compiler=self.c_compiler(),
  File "/home/travis/miniconda/envs/test-environment/lib/python2.7/site-packages/theano/gof/cc.py", line 1379, in cmodule_key_
    np.core.multiarray._get_ndarray_c_version())
AttributeError: ('The following error happened while compiling the node', Elemwise{add,no_inplace}(x, y), '\n', "'module' object has no attribute '_get_ndarray_c_version'")
________________________________________________________________________________
______ sympy/printing/tests/test_theanocode.py:test_theano_function_multi ______
Traceback (most recent call last):
  File "/home/travis/miniconda/envs/test-environment/lib/python2.7/site-packages/sympy-1.4.dev0-py2.7.egg/sympy/utilities/runtests.py", line 1306, in _timeout
    function()
  File "/home/travis/miniconda/envs/test-environment/lib/python2.7/site-packages/sympy-1.4.dev0-py2.7.egg/sympy/printing/tests/test_theanocode.py", line 282, in test_theano_function_multi
    f = theano_function_([x, y], [x+y, x-y])
  File "/home/travis/miniconda/envs/test-environment/lib/python2.7/site-packages/sympy-1.4.dev0-py2.7.egg/sympy/printing/tests/test_theanocode.py", line 54, in theano_function_
    return theano_function(inputs, outputs, **kwargs)
  File "/home/travis/miniconda/envs/test-environment/lib/python2.7/site-packages/sympy-1.4.dev0-py2.7.egg/sympy/printing/theanocode.py", line 500, in theano_function
    func = theano.function(tinputs, toutputs, **kwargs)
  File "/home/travis/miniconda/envs/test-environment/lib/python2.7/site-packages/theano/compile/function.py", line 317, in function
    output_keys=output_keys)
  File "/home/travis/miniconda/envs/test-environment/lib/python2.7/site-packages/theano/compile/pfunc.py", line 486, in pfunc
    output_keys=output_keys)
  File "/home/travis/miniconda/envs/test-environment/lib/python2.7/site-packages/theano/compile/function_module.py", line 1841, in orig_function
    fn = m.create(defaults)
  File "/home/travis/miniconda/envs/test-environment/lib/python2.7/site-packages/theano/compile/function_module.py", line 1715, in create
    input_storage=input_storage_lists, storage_map=storage_map)
  File "/home/travis/miniconda/envs/test-environment/lib/python2.7/site-packages/theano/gof/link.py", line 699, in make_thunk
    storage_map=storage_map)[:3]
  File "/home/travis/miniconda/envs/test-environment/lib/python2.7/site-packages/theano/gof/vm.py", line 1091, in make_all
    impl=impl))
  File "/home/travis/miniconda/envs/test-environment/lib/python2.7/site-packages/theano/gof/op.py", line 955, in make_thunk
    no_recycling)
  File "/home/travis/miniconda/envs/test-environment/lib/python2.7/site-packages/theano/gof/op.py", line 858, in make_c_thunk
    output_storage=node_output_storage)
  File "/home/travis/miniconda/envs/test-environment/lib/python2.7/site-packages/theano/gof/cc.py", line 1217, in make_thunk
    keep_lock=keep_lock)
  File "/home/travis/miniconda/envs/test-environment/lib/python2.7/site-packages/theano/gof/cc.py", line 1157, in __compile__
    keep_lock=keep_lock)
  File "/home/travis/miniconda/envs/test-environment/lib/python2.7/site-packages/theano/gof/cc.py", line 1609, in cthunk_factory
    key = self.cmodule_key()
  File "/home/travis/miniconda/envs/test-environment/lib/python2.7/site-packages/theano/gof/cc.py", line 1300, in cmodule_key
    c_compiler=self.c_compiler(),
  File "/home/travis/miniconda/envs/test-environment/lib/python2.7/site-packages/theano/gof/cc.py", line 1379, in cmodule_key_
    np.core.multiarray._get_ndarray_c_version())
AttributeError: ('The following error happened while compiling the node', Elemwise{add,no_inplace}(x, y), '\n', "'module' object has no attribute '_get_ndarray_c_version'")
________________________________________________________________________________
______ sympy/printing/tests/test_theanocode.py:test_theano_function_numpy ______
Traceback (most recent call last):
  File "/home/travis/miniconda/envs/test-environment/lib/python2.7/site-packages/sympy-1.4.dev0-py2.7.egg/sympy/utilities/runtests.py", line 1306, in _timeout
    function()
  File "/home/travis/miniconda/envs/test-environment/lib/python2.7/site-packages/sympy-1.4.dev0-py2.7.egg/sympy/printing/tests/test_theanocode.py", line 290, in test_theano_function_numpy
    dtypes={x: 'float64', y: 'float64'})
  File "/home/travis/miniconda/envs/test-environment/lib/python2.7/site-packages/sympy-1.4.dev0-py2.7.egg/sympy/printing/tests/test_theanocode.py", line 54, in theano_function_
    return theano_function(inputs, outputs, **kwargs)
  File "/home/travis/miniconda/envs/test-environment/lib/python2.7/site-packages/sympy-1.4.dev0-py2.7.egg/sympy/printing/theanocode.py", line 500, in theano_function
    func = theano.function(tinputs, toutputs, **kwargs)
  File "/home/travis/miniconda/envs/test-environment/lib/python2.7/site-packages/theano/compile/function.py", line 317, in function
    output_keys=output_keys)
  File "/home/travis/miniconda/envs/test-environment/lib/python2.7/site-packages/theano/compile/pfunc.py", line 486, in pfunc
    output_keys=output_keys)
  File "/home/travis/miniconda/envs/test-environment/lib/python2.7/site-packages/theano/compile/function_module.py", line 1841, in orig_function
    fn = m.create(defaults)
  File "/home/travis/miniconda/envs/test-environment/lib/python2.7/site-packages/theano/compile/function_module.py", line 1715, in create
    input_storage=input_storage_lists, storage_map=storage_map)
  File "/home/travis/miniconda/envs/test-environment/lib/python2.7/site-packages/theano/gof/link.py", line 699, in make_thunk
    storage_map=storage_map)[:3]
  File "/home/travis/miniconda/envs/test-environment/lib/python2.7/site-packages/theano/gof/vm.py", line 1091, in make_all
    impl=impl))
  File "/home/travis/miniconda/envs/test-environment/lib/python2.7/site-packages/theano/gof/op.py", line 955, in make_thunk
    no_recycling)
  File "/home/travis/miniconda/envs/test-environment/lib/python2.7/site-packages/theano/gof/op.py", line 858, in make_c_thunk
    output_storage=node_output_storage)
  File "/home/travis/miniconda/envs/test-environment/lib/python2.7/site-packages/theano/gof/cc.py", line 1217, in make_thunk
    keep_lock=keep_lock)
  File "/home/travis/miniconda/envs/test-environment/lib/python2.7/site-packages/theano/gof/cc.py", line 1157, in __compile__
    keep_lock=keep_lock)
  File "/home/travis/miniconda/envs/test-environment/lib/python2.7/site-packages/theano/gof/cc.py", line 1609, in cthunk_factory
    key = self.cmodule_key()
  File "/home/travis/miniconda/envs/test-environment/lib/python2.7/site-packages/theano/gof/cc.py", line 1300, in cmodule_key
    c_compiler=self.c_compiler(),
  File "/home/travis/miniconda/envs/test-environment/lib/python2.7/site-packages/theano/gof/cc.py", line 1379, in cmodule_key_
    np.core.multiarray._get_ndarray_c_version())
AttributeError: ('The following error happened while compiling the node', Elemwise{add,no_inplace}(x, y), '\n', "'module' object has no attribute '_get_ndarray_c_version'")
________________________________________________________________________________
_____ sympy/printing/tests/test_theanocode.py:test_theano_function_matrix ______
Traceback (most recent call last):
  File "/home/travis/miniconda/envs/test-environment/lib/python2.7/site-packages/sympy-1.4.dev0-py2.7.egg/sympy/utilities/runtests.py", line 1306, in _timeout
    function()
  File "/home/travis/miniconda/envs/test-environment/lib/python2.7/site-packages/sympy-1.4.dev0-py2.7.egg/sympy/printing/tests/test_theanocode.py", line 303, in test_theano_function_matrix
    f = theano_function_([x, y, z], [m])
  File "/home/travis/miniconda/envs/test-environment/lib/python2.7/site-packages/sympy-1.4.dev0-py2.7.egg/sympy/printing/tests/test_theanocode.py", line 54, in theano_function_
    return theano_function(inputs, outputs, **kwargs)
  File "/home/travis/miniconda/envs/test-environment/lib/python2.7/site-packages/sympy-1.4.dev0-py2.7.egg/sympy/printing/theanocode.py", line 500, in theano_function
    func = theano.function(tinputs, toutputs, **kwargs)
  File "/home/travis/miniconda/envs/test-environment/lib/python2.7/site-packages/theano/compile/function.py", line 317, in function
    output_keys=output_keys)
  File "/home/travis/miniconda/envs/test-environment/lib/python2.7/site-packages/theano/compile/pfunc.py", line 486, in pfunc
    output_keys=output_keys)
  File "/home/travis/miniconda/envs/test-environment/lib/python2.7/site-packages/theano/compile/function_module.py", line 1841, in orig_function
    fn = m.create(defaults)
  File "/home/travis/miniconda/envs/test-environment/lib/python2.7/site-packages/theano/compile/function_module.py", line 1715, in create
    input_storage=input_storage_lists, storage_map=storage_map)
  File "/home/travis/miniconda/envs/test-environment/lib/python2.7/site-packages/theano/gof/link.py", line 699, in make_thunk
    storage_map=storage_map)[:3]
  File "/home/travis/miniconda/envs/test-environment/lib/python2.7/site-packages/theano/gof/vm.py", line 1091, in make_all
    impl=impl))
  File "/home/travis/miniconda/envs/test-environment/lib/python2.7/site-packages/theano/gof/op.py", line 955, in make_thunk
    no_recycling)
  File "/home/travis/miniconda/envs/test-environment/lib/python2.7/site-packages/theano/gof/op.py", line 858, in make_c_thunk
    output_storage=node_output_storage)
  File "/home/travis/miniconda/envs/test-environment/lib/python2.7/site-packages/theano/gof/cc.py", line 1217, in make_thunk
    keep_lock=keep_lock)
  File "/home/travis/miniconda/envs/test-environment/lib/python2.7/site-packages/theano/gof/cc.py", line 1157, in __compile__
    keep_lock=keep_lock)
  File "/home/travis/miniconda/envs/test-environment/lib/python2.7/site-packages/theano/gof/cc.py", line 1609, in cthunk_factory
    key = self.cmodule_key()
  File "/home/travis/miniconda/envs/test-environment/lib/python2.7/site-packages/theano/gof/cc.py", line 1300, in cmodule_key
    c_compiler=self.c_compiler(),
  File "/home/travis/miniconda/envs/test-environment/lib/python2.7/site-packages/theano/gof/cc.py", line 1379, in cmodule_key_
    np.core.multiarray._get_ndarray_c_version())
AttributeError: ('The following error happened while compiling the node', Elemwise{add,no_inplace}(x, y, z), '\n', "'module' object has no attribute '_get_ndarray_c_version'")
________________________________________________________________________________
_____ sympy/printing/tests/test_theanocode.py:test_theano_function_kwargs ______
Traceback (most recent call last):
  File "/home/travis/miniconda/envs/test-environment/lib/python2.7/site-packages/sympy-1.4.dev0-py2.7.egg/sympy/utilities/runtests.py", line 1306, in _timeout
    function()
  File "/home/travis/miniconda/envs/test-environment/lib/python2.7/site-packages/sympy-1.4.dev0-py2.7.egg/sympy/printing/tests/test_theanocode.py", line 324, in test_theano_function_kwargs
    dtypes={x: 'float64', y: 'float64', z: 'float64'})
  File "/home/travis/miniconda/envs/test-environment/lib/python2.7/site-packages/sympy-1.4.dev0-py2.7.egg/sympy/printing/tests/test_theanocode.py", line 54, in theano_function_
    return theano_function(inputs, outputs, **kwargs)
  File "/home/travis/miniconda/envs/test-environment/lib/python2.7/site-packages/sympy-1.4.dev0-py2.7.egg/sympy/printing/theanocode.py", line 500, in theano_function
    func = theano.function(tinputs, toutputs, **kwargs)
  File "/home/travis/miniconda/envs/test-environment/lib/python2.7/site-packages/theano/compile/function.py", line 317, in function
    output_keys=output_keys)
  File "/home/travis/miniconda/envs/test-environment/lib/python2.7/site-packages/theano/compile/pfunc.py", line 486, in pfunc
    output_keys=output_keys)
  File "/home/travis/miniconda/envs/test-environment/lib/python2.7/site-packages/theano/compile/function_module.py", line 1841, in orig_function
    fn = m.create(defaults)
  File "/home/travis/miniconda/envs/test-environment/lib/python2.7/site-packages/theano/compile/function_module.py", line 1715, in create
    input_storage=input_storage_lists, storage_map=storage_map)
  File "/home/travis/miniconda/envs/test-environment/lib/python2.7/site-packages/theano/gof/link.py", line 699, in make_thunk
    storage_map=storage_map)[:3]
  File "/home/travis/miniconda/envs/test-environment/lib/python2.7/site-packages/theano/gof/vm.py", line 1091, in make_all
    impl=impl))
  File "/home/travis/miniconda/envs/test-environment/lib/python2.7/site-packages/theano/gof/op.py", line 955, in make_thunk
    no_recycling)
  File "/home/travis/miniconda/envs/test-environment/lib/python2.7/site-packages/theano/gof/op.py", line 858, in make_c_thunk
    output_storage=node_output_storage)
  File "/home/travis/miniconda/envs/test-environment/lib/python2.7/site-packages/theano/gof/cc.py", line 1217, in make_thunk
    keep_lock=keep_lock)
  File "/home/travis/miniconda/envs/test-environment/lib/python2.7/site-packages/theano/gof/cc.py", line 1157, in __compile__
    keep_lock=keep_lock)
  File "/home/travis/miniconda/envs/test-environment/lib/python2.7/site-packages/theano/gof/cc.py", line 1609, in cthunk_factory
    key = self.cmodule_key()
  File "/home/travis/miniconda/envs/test-environment/lib/python2.7/site-packages/theano/gof/cc.py", line 1300, in cmodule_key
    c_compiler=self.c_compiler(),
  File "/home/travis/miniconda/envs/test-environment/lib/python2.7/site-packages/theano/gof/cc.py", line 1379, in cmodule_key_
    np.core.multiarray._get_ndarray_c_version())
AttributeError: ('The following error happened while compiling the node', Elemwise{add,no_inplace}(x, y), '\n', "'module' object has no attribute '_get_ndarray_c_version'")
________________________________________________________________________________
_____ sympy/printing/tests/test_theanocode.py:test_theano_function_scalar ______
Traceback (most recent call last):
  File "/home/travis/miniconda/envs/test-environment/lib/python2.7/site-packages/sympy-1.4.dev0-py2.7.egg/sympy/utilities/runtests.py", line 1306, in _timeout
    function()
  File "/home/travis/miniconda/envs/test-environment/lib/python2.7/site-packages/sympy-1.4.dev0-py2.7.egg/sympy/printing/tests/test_theanocode.py", line 350, in test_theano_function_scalar
    f = theano_function_(inputs, outputs, dims=in_dims, scalar=scalar)
  File "/home/travis/miniconda/envs/test-environment/lib/python2.7/site-packages/sympy-1.4.dev0-py2.7.egg/sympy/printing/tests/test_theanocode.py", line 54, in theano_function_
    return theano_function(inputs, outputs, **kwargs)
  File "/home/travis/miniconda/envs/test-environment/lib/python2.7/site-packages/sympy-1.4.dev0-py2.7.egg/sympy/printing/theanocode.py", line 500, in theano_function
    func = theano.function(tinputs, toutputs, **kwargs)
  File "/home/travis/miniconda/envs/test-environment/lib/python2.7/site-packages/theano/compile/function.py", line 317, in function
    output_keys=output_keys)
  File "/home/travis/miniconda/envs/test-environment/lib/python2.7/site-packages/theano/compile/pfunc.py", line 486, in pfunc
    output_keys=output_keys)
  File "/home/travis/miniconda/envs/test-environment/lib/python2.7/site-packages/theano/compile/function_module.py", line 1841, in orig_function
    fn = m.create(defaults)
  File "/home/travis/miniconda/envs/test-environment/lib/python2.7/site-packages/theano/compile/function_module.py", line 1715, in create
    input_storage=input_storage_lists, storage_map=storage_map)
  File "/home/travis/miniconda/envs/test-environment/lib/python2.7/site-packages/theano/gof/link.py", line 699, in make_thunk
    storage_map=storage_map)[:3]
  File "/home/travis/miniconda/envs/test-environment/lib/python2.7/site-packages/theano/gof/vm.py", line 1091, in make_all
    impl=impl))
  File "/home/travis/miniconda/envs/test-environment/lib/python2.7/site-packages/theano/gof/op.py", line 955, in make_thunk
    no_recycling)
  File "/home/travis/miniconda/envs/test-environment/lib/python2.7/site-packages/theano/gof/op.py", line 858, in make_c_thunk
    output_storage=node_output_storage)
  File "/home/travis/miniconda/envs/test-environment/lib/python2.7/site-packages/theano/gof/cc.py", line 1217, in make_thunk
    keep_lock=keep_lock)
  File "/home/travis/miniconda/envs/test-environment/lib/python2.7/site-packages/theano/gof/cc.py", line 1157, in __compile__
    keep_lock=keep_lock)
  File "/home/travis/miniconda/envs/test-environment/lib/python2.7/site-packages/theano/gof/cc.py", line 1609, in cthunk_factory
    key = self.cmodule_key()
  File "/home/travis/miniconda/envs/test-environment/lib/python2.7/site-packages/theano/gof/cc.py", line 1300, in cmodule_key
    c_compiler=self.c_compiler(),
  File "/home/travis/miniconda/envs/test-environment/lib/python2.7/site-packages/theano/gof/cc.py", line 1379, in cmodule_key_
    np.core.multiarray._get_ndarray_c_version())
AttributeError: ('The following error happened while compiling the node', Elemwise{add,no_inplace}(x, y), '\n', "'module' object has no attribute '_get_ndarray_c_version'")
========== tests finished: 833 passed, 6 exceptions, in 24.98 seconds ==========
DO *NOT* COMMIT!
Traceback (most recent call last):
  File "<stdin>", line 10, in <module>
Exception: Tests failed
```

**Comment by smichr** [comment]
Are you able to bisect to see which commit made it start failing?

**Comment by sylee957** [comment]
I think it had started failing after merging https://github.com/sympy/sympy/commit/9d53296873723e7a3a287b7508669f830c300400

**Comment by sylee957** [comment]
There is no difference in theano version, but I think numpy version had changed from 1.15.4 to 1.16.0 between the merges

**Comment by sylee957** [comment]
It may be related to the upstream issue https://github.com/Theano/Theano/pull/6671

**Comment by oscargus** [comment]
I second that it relates to the numpy update and not the most recent merge. Maybe a way would be to use an earlier numpy version until it is solved?

**Comment by oscargus** [comment]
Looks like #15785 will fix it. Just have to wait for the latest tests to finish.

**Comment by nouiz** [comment]
We just released Theano 1.0.4 that added support for numpy 1.16 on the CPU. We didn't test on the GPU.

**Comment by sylee957** [comment]
I think theano issue is resolved. But sage test is still not working
