### PR TITLE
[WIP]AST transformer for isympy(IPython console)

### LINKED ISSUE #11419: init_session() on ipython startup file a different mainloop
I am trying to have a startup script for an IPython profile that calls `init_session()`. It seems doing this starts a different IPython mainloop. I can exit it with `C-d` and then get to the IPython prompt.

I think this has to do with wrongly assuming we are not inside IPython during startup:

```
/home/elvis/miniconda3/envs/sci/lib/python3.5/site-packages/sympy/interactive/session.py in init_session(ipython, pretty_print, order, use_unicode, use_latex, quiet, auto_symbols, auto_int_to_Integer, str_printer, pretty_printer, latex_printer, argv)
    472     if not in_ipython:
    473         mainloop(message)
--> 474         sys.exit('Exiting ...')
    475     else:
    476         ip.write(message)

SystemExit: Exiting ...
```

### LINKED ISSUE #13027: Lambdify with `modules='numpy'` fails when `auto_int_to_Integer=True`
Every input in the `sympy-live` shell is processed using `int_to_Integer` (converts Python `int` to sympy `Integer`s) because this makes it much nicer. Not sure but maybe some of the example in the docs also assume this behaviour.

While trying to understand some bugs in `sympy-live` related to `numpy`-lambdification, I was able to isolate the following bug that appears to exist in `sympy` (1.1 and 1.1.1rc1).

To reproduce, `pip install sympy numpy` then run
```
import numpy
import sympy
sympy.init_session(auto_int_to_Integer=True)
print 'using sympy', sympy.__version__, 'and numpy', numpy.__version__
```
wait a second then run
```
x = sympy.symbols('x')
expr = sympy.sin(x)
f = sympy.lambdify(x, expr, "numpy")
a = 3
print( f(3) )
```

This results in 
```
using sympy 1.1 and numpy 1.13.1
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-2-a8c650daaf7d> in <module>()
      3 f =sympy .lambdify (x ,expr ,"numpy")
      4 a =Integer (3 )
----> 5 print (f (Integer (3 )))

/int_to_Int_lambdify_bug/venv/lib/python2.7/site-packages/sympy/utilities/lambdify.pyc in wrapper(*argsx, **kwargsx)
    439             @wraps(funcarg)
    440             def wrapper(*argsx, **kwargsx):
--> 441                 return funcarg(*[namespace['asarray'](i) for i in argsx], **kwargsx)
    442             return wrapper
    443         func = array_wrap(func)

/int_to_Int_lambdify_bug/venv/lib/python2.7/site-packages/numpy/__init__.pyc in <lambda>(_Dummy_140)
AttributeError: 'Integer' object has no attribute 'sin'
```

I saw there is some work on `lambdify`-related work in `1.1.1`  so I tried that too using

```
pip install git+git://github.com/sympy/sympy.git@1.1.1#egg=sympy
```
and running the same code as above produced
```
using sympy 1.1.1rc1 and numpy 1.13.1

In [2]: x = sympy.symbols('x')
   ...: expr = sympy.sin(x)
   ...: f = sympy.lambdify(x, expr, "numpy")
   ...: a = 3
   ...: print( f(3) )
   ...:
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-2-a8c650daaf7d> in <module>()
      3 f =sympy .lambdify (x ,expr ,"numpy")
      4 a =Integer (3 )
----> 5 print (f (Integer (3 )))

/int_to_Int_lambdify_bug/venv/lib/python2.7/site-packages/sympy/utilities/lambdify.pyc in wrapper(*argsx, **kwargsx)
    442                 newargs = [asarray(i) if isinstance(i, integer_types + (float,
    443                     complex)) else i for i in argsx]
--> 444                 return funcarg(*newargs, **kwargsx)
    445             return wrapper
    446         func = array_wrap(func)

/int_to_Int_lambdify_bug/venv/lib/python2.7/site-packages/numpy/__init__.pyc in <lambda>(_Dummy_140)
AttributeError: 'Integer' object has no attribute 'sin'
```

### LINKED ISSUE #13319: MultipleInstanceError with init_session from notebook or qtconsole
Running sympy.init_session() from a jupyter notebook or qtconsole gives the exception:

> MultipleInstanceError: Multiple incompatible subclass instances of TerminalInteractiveShell are being created.

sympy.init_session(ipython=False) works (although it starts a subshell in the same notebook cell, with its own "In: " input box, so the if anything is entered into the other cells of the notebook, they wait for the init_session cell to terminate, which it does not do with either "quit", "quit()" or "^D").

In addition, sympy.init_session(ipython=False, auto_int_to_Integer=True) gives

> RuntimeError: automatic int to Integer transformation is possible only in IPython 0.11 or above

not because I have Ipython.__version__ < 0.11 (I have 6.1), but because ipython is False.

All this works fine from an ordinary terminal-based ipython session.

Is there any way to properly initialize a sympy session from within a notebook or qtconsole, preferably with auto_int_to_Integer=True? I haven't been able to find one despite spending an afternoon on it!

### LINKED ISSUE #13418: init_session() gives MultipleInstanceError in qtconsole
First an error message when trying `init_session`:

```
Jupyter QtConsole 4.3.1
Python 3.5.4 | packaged by conda-forge | (default, Aug 10 2017, 01:38:41) 
Type 'copyright', 'credits' or 'license' for more information
IPython 6.2.1 -- An enhanced Interactive Python. Type '?' for help.

import sympy as sm

sm.__version__
Out[2]: '1.1.1'

sm.init_session()
---------------------------------------------------------------------------
MultipleInstanceError                     Traceback (most recent call last)
<ipython-input-3-cfcb97dfecd3> in <module>()
----> 1 sm.init_session()

~/miniconda3/lib/python3.5/site-packages/sympy/interactive/session.py in init_session(ipython, pretty_print, order, use_unicode, use_latex, quiet, auto_symbols, auto_int_to_Integer, str_printer, pretty_printer, latex_printer, argv)
    431     else:
    432         ip = init_ipython_session(argv=argv, auto_symbols=auto_symbols,
--> 433             auto_int_to_Integer=auto_int_to_Integer)
    434 
    435         if V(IPython.__version__) >= '0.11':

~/miniconda3/lib/python3.5/site-packages/sympy/interactive/session.py in init_ipython_session(argv, auto_symbols, auto_int_to_Integer)
    262         # don't draw IPython banner during initialization:
    263         app.display_banner = False
--> 264         app.initialize(argv)
    265 
    266         if auto_symbols:

<decorator-gen-112> in initialize(self, argv)

~/miniconda3/lib/python3.5/site-packages/traitlets/config/application.py in catch_config_error(method, app, *args, **kwargs)
     85     """
     86     try:
---> 87         return method(app, *args, **kwargs)
     88     except (TraitError, ArgumentError) as e:
     89         app.print_help()

~/miniconda3/lib/python3.5/site-packages/IPython/terminal/ipapp.py in initialize(self, argv)
    315         self.init_path()
    316         # create the shell
--> 317         self.init_shell()
    318         # and draw the banner
    319         self.init_banner()

~/miniconda3/lib/python3.5/site-packages/IPython/terminal/ipapp.py in init_shell(self)
    331         self.shell = self.interactive_shell_class.instance(parent=self,
    332                         profile_dir=self.profile_dir,
--> 333                         ipython_dir=self.ipython_dir, user_ns=self.user_ns)
    334         self.shell.configurables.append(self)
    335 

~/miniconda3/lib/python3.5/site-packages/traitlets/config/configurable.py in instance(cls, *args, **kwargs)
    421             raise MultipleInstanceError(
    422                 'Multiple incompatible subclass instances of '
--> 423                 '%s are being created.' % cls.__name__
    424             )
    425 

MultipleInstanceError: Multiple incompatible subclass instances of TerminalInteractiveShell are being created.
```

### PR DESCRIPTION
**Pull request by ylemkimon**
- Implement AST transformers(IntegerWrapper and AutomaticSymbols) from Diofant(@skirpichev)
- Add automatic rationalization option: automatically wraps `float` with `Rational`, e.g., `0.5` to `Rational('0.5')`

* [ ] Implement token-based transformers or use IPython token-based transformer: #14440

- ~Change `optparse` to `argparse`: `optparse` is deprecated since Python version 2.7~
- ~Use existing IPython shell if present, when initializing new IPython session: Fixes #13418, fixes #13319, and fixes #11419.~
- ~Fixed incorrect architecture detection on 64-bit Windows. [(SO)](https://stackoverflow.com/q/1405913/1448742)~

Split into #14443 and #14440.

### CODE REVIEW

**Comment by jksuom** [comment]
I think that IPython support should not be removed yet. SymPy works quite well with older versions.

**Comment by asmeurer** [comment]
Also be aware of https://github.com/sympy/sympy/pull/13193

**Comment by skirpichev** [comment]
> I think that IPython support should not be removed yet. SymPy works quite well with older versions.

Support for user-added AST transformations added, according to IPython log, in 1.0.0.

Any rational arguments for keeping compatibility with ancient IPython versions, where most isympy options will not work?

**Comment by ylemkimon** [comment]
@jksuom Instead of removing IPython < 1.0 support, added ast_transformers support for IPython < 1.0 by monkey-patching run_ast_nodes.

**Comment by ylemkimon** [comment]
Should we remove `sympy.interactive.session.int_to_Integer`, deprecate it, or leave as is?

**Comment by asmeurer** [comment]
I wonder if we can move the command line option help into the command line options, so that it doesn't show them twice. I'm assuming it was done the way it is now because of some optparse limitations.

File: sympy/interactive/session.py [hunk 1]
```diff
@@ -85,6 +90,76 @@ def _make_message(ipython=True, quiet=False, source=None):
...
+        return node
+
+
+class FloatRationalizer(ast.NodeTransformer):
+    """Wraps all floats in a call to Rational."""
+
+    def visit_Num(self, node):
+        if isinstance(node.n, float):
+            return ast.Call(func=ast.Name(id='Rational', ctx=ast.Load()),
+                            args=[ast.Str(s=repr(node.n))], keywords=[],
```
Comment (asmeurer) [inline sympy/interactive/session.py]: Is it possible to use the exact string form? If you enter a float that has more precision than a Python float, like `1.00000000000000000001`, it gets rounded before being wrapped.

**Comment by asmeurer** [comment]
We should probably do some manual testing for older versions of Python, and also for the notebook and qtconsole.

File: sympy/interactive/session.py (hunk 1 above)
Comment (skirpichev) [reply sympy/interactive/session.py]: Not with ast.  It sees not a "string form", but a float literal.  Which is 1.0 in this case.

Comment (asmeurer) [reply sympy/interactive/session.py]: I think you may be able to "find" the original float by tokenizing the input string and looking for the literal with the appropriate col_offset and lineno. I don't know if it will be robust, though.

Comment (asmeurer) [reply sympy/interactive/session.py]: I'm not suggesting to tokenize - transform - untokenize (as we did before with Integer wrapping). That has issues, such as changing the code that's shown in tracebacks. You still use an ast transformer, but instead of using node.n, you use tokenize the input string, then match up the token that has the corresponding node.col_offset and lineno.  This is assuming the full original input string is available from the IPython API.

Comment (asmeurer) [reply sympy/interactive/session.py]: For example:

```py
>>> ast.parse('2 + 1.0000000000000001').body[0].value.right.lineno
1
>>> ast.parse('2 + 1.0000000000000001').body[0].value.right.col_offset
4
>>> for token in tokenize.tokenize(io.BytesIO('2 + 1.0000000000000001'.encode('utf-8')).readline):
...     print(token)
TokenInfo(type=59 (BACKQUOTE), string='utf-8', start=(0, 0), end=(0, 0), line='')
TokenInfo(type=2 (NUMBER), string='2', start=(1, 0), end=(1, 1), line='2 + 1.0000000000000001')
TokenInfo(type=53 (OP), string='+', start=(1, 2), end=(1, 3), line='2 + 1.0000000000000001')
TokenInfo(type=2 (NUMBER), string='1.0000000000000001', start=(1, 4), end=(1, 22), line='2 + 1.0000000000000001')
TokenInfo(type=0 (ENDMARKER), string='', start=(2, 0), end=(2, 0), line='')
```

So (1, 4) corresponds to the token `TokenInfo(type=2 (NUMBER), string='1.000000000001', start=(1, 4), end=(1, 18), line='2 + 1.000000000001')`, which has the original string

**Comment by ylemkimon** [comment]
@asmeurer `argparse` still doesn't support argument help formatting. However, we can hide it by setting `help=argparse.SUPPRESS`. Also, tested it on IPython 0.13, 1.0, and latest version.

File: sympy/interactive/session.py (hunk 1 above)
Comment (ylemkimon) [reply sympy/interactive/session.py]: @asmeurer The input string is not passed to `run_ast_nodes` nor available to AST transformers. We'd have to monkey-patch `run_cell`, but I'm afraid there is a lot of processing between `run_cell` call and AST transformation.

Comment (ylemkimon) [reply sympy/interactive/session.py]: @asmeurer I'm not sure why showing transformed input in the traceback is a problem. IPython already does that for string-based transformers and line magics, and it may be more informative to users.

Comment (skirpichev) [reply sympy/interactive/session.py]: > You still use an ast transformer, but instead of using node.n, you use tokenize the input string

This may work only if NodeTransformer will not shift original col_offset/lineno after modifications.

> We have to monkey-patch run_cell

No.  You just can use other available IPython transformations, string-based.  And parse & run ast transformation here, together with tokenization.

But IMHO, this way just overkill c.f. simple tokenize->fix->untokenize.

> I'm not suggesting to tokenize -> transform -> untokenize (as we did before with Integer wrapping). That has issues, such as changing the code that's shown in tracebacks.

I bet, it doesn't related to using tokenize, but to your monkey-patched run_cell() method.  You should use provided by IPython API, namely string-based input (registered in python_line_transforms).

**Comment by skirpichev** [comment]
> argparse still doesn't support argument help formatting.

What do you mean?  Hack with using module \__doc__'s - could be fully replaced by argparse.   Parameter description could be formatted arbitrarily complex (multiple lines, indentation, etc).

File: sympy/interactive/session.py (hunk 1 above)
Comment (asmeurer) [reply sympy/interactive/session.py]: If a tokenize based transformer is no worse than an ast transformer then why are we changing to ast transformers in the first place?

Comment (skirpichev) [reply sympy/interactive/session.py]: Good question for PR owner.  But lets make it clear: currently sympy doesn't use **any** IPython API for transformers.  Nor ast transformers, nor string-based.

Comment (ylemkimon) [reply sympy/interactive/session.py]: @asmeurer As you said, IPython ast transformers do not show transformed input in the traceback–though I’m not sure it’s neccessary. This PR aims to use IPython APIs for better compatibility, since as @skirpichev said, it currently monkey-patches IPython.

**Comment by asmeurer** [comment]
Should the float -> rational flag also enable the integer wrapping flag? With just `-r`, we have

```py
In [1]: 1/2
Out[1]: 0.5

In [2]: 0.5
Out[2]: 1/2
```

**Comment by ylemkimon** [comment]
@asmeurer I think so. If use cases overlap, we should consider combining both option as `-rationalize`, since it rationalizes floats and integer divisions.

File: sympy/interactive/session.py (hunk 1 above)
Comment (ylemkimon) [reply sympy/interactive/session.py]: Also, if we use string-based or token-based transformers, maybe we can hook existing transformers at `sympy.parsing.sympy_parser` like `convert_xor`.

Comment (asmeurer) [reply sympy/interactive/session.py]: How does IPython handle its extensions of Python (like magics), which can appear inside of Python statements, like

```
for i in range(10):
    %time i + 1
```

Does IPython have a special Python parser, or is it simpler than that? 

I agree that an xor extension would also be useful, and it has to happen at tokenization, before the Python AST is created, due to they way ^ is parsed (it has a different precedence than **, so `x + y^2` would be `Xor(Add(x, y), 2)` in the AST).

**Comment by ylemkimon** [comment]
I've opened an issue regarding TokenInputTransformer: https://github.com/ipython/ipython/issues/10893

File: sympy/interactive/session.py (hunk 1 above)
Comment (ylemkimon) [reply sympy/interactive/session.py]: @asmeurer IPython just processes line by line, and look for magic commands starting with percent signs, at the start of line and preprocesses it before passing to Python.

**Comment by asmeurer** [comment]
It looks like https://github.com/sympy/sympy/pull/14443 is a better PR to merge for now. Although I did test `-r` and it seems to work (it should be added to `-I` though).
