### ISSUE TITLE
Cannot transpose matrix multiplied by scalar

### ISSUE THREAD

**Issue by david-cortes** [sympy/sympy#17962]
The following will fail:
```python
from sympy import *
c = symbols('c')
m = symbols('m')
n = symbols('n')
A = MatrixSymbol('A', m, n)
(c * A).T
```
```
AttributeError: 'Symbol' object has no attribute 'shape'
```

Transposing beforehand will not present any issue:
```python
c * (A.T)
```

**Comment by ethankward** [comment]
Fixed in master. Broken by commit 028708996ac3eec113ef0f4d7fcb1210f3ed6cb6. Fixed by commit 8479bd6b8a752c8d3908edbe86ad924ccf7be736.
