### PR TITLE
Tweak .core.relational._canoncial_coeff to fix gh-27538 (alt)

### LINKED ISSUE #27538: Regression in Piecewise when xreplacing involing a Relational (sympy-1.9 -- sympy-1.10)
Here's a script to find the regression:
```bash
#!/bin/bash                                                                                                                                                                                                                                                                   
cat <<EOF >bisect-regression.py                                                                                                                                                                                                                                               
from sympy import symbols, Piecewise, Equality, true                                                                                                                                                                                                                          
x, y = symbols('x, y')                                                                                                                                                                                                                                                        
p1 = Piecewise(                                                                                                                                                                                                                                                               
    (0, Equality(x, true)),                                                                                                                                                                                                                                                   
    (1, true),                                                                                                                                                                                                                                                                
)                                                                                                                                                                                                                                                                             
p2 = p1.xreplace({x: y < 1})                                                                                                                                                                                                                                                  
assert p2.subs(y, 0) == 0                                                                                                                                                                                                                                                     
assert p2.subs(y, 1) == 1                                                                                                                                                                                                                                                     
EOF                                                                                                                                                                                                                                                                           
git bisect start --first-parent sympy-1.10 sympy-1.9                                                                                                                                                                                                                          
git bisect run python bisect-regression.py
```

<details>
<summary>$ ./bisect-regression.sh</summary>


```
[930efd2907a9d6c15500e0aa3d5507691dbb297b] Merge pull request #22358 from PGijsbers/18521_limits
running  'python' 'bisect-regression.py'
4282433901d3159a485866ce0d93aefe531ffbc7 is the first bad commit
commit 4282433901d3159a485866ce0d93aefe531ffbc7
Merge: 930efd2907 d02946955f
Author: Christopher Smith <smichr@gmail.com>
Date:   Sun Oct 24 04:20:27 2021 -0500

    Merge pull request #22286 from smichr/pwmeij
    
    modify _condsimp to handle missed cases; remove expensive steps from Piecewise.eval
```

</details>
It identifies gh-22286 as the PR introducing the regression (I don't blame anyone for that of course, our test coverage isn't always the best).

One way to resolve this would be to patch `_canonical_coeff` in `.core.relational` (introduced in the referenced PR), so that it handles `Relational`s with `BooleanTrue`/`BooleanFalse` in either `lhs` or `rhs`. But if someone knows a better way, let me know, otherwise I'll try to whip up a PR doing just that.

### PR DESCRIPTION
**Pull request by bjodah**
#### References to other Issues or PRs
Fixes #27538

#### Brief description of what is fixed or changed
Fixes a regression involving Piecewise and Relationals:
```console-session
  File "/opt-3/cpython-v3.12-apt-deb/lib/python3.12/site-packages/sympy/core/relational.py", line 55, in _canonical_coeff
    b, l = rel.lhs.as_coeff_Add(rational=True)
           ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'BooleanTrue' object has no attribute 'as_coeff_Add'
```

#### Other comments
This is an alternative to gh-27539, here we use `isinstance(..., Expr)` instead of `.is_Boolean` for `rel.lhs`.

#### Release Notes

* core
   * A bug in Relational was fixed. Previously operations involving an expression like `Eq(y < 1, True)` might raise an exception.

### CODE REVIEW

**Comment by oscarbenjamin** [comment]
Looks good.

**Comment by bjodah** [comment]
Thank you for the review.
