### PR TITLE
Fix: Allow multiplication of basis vectors by float zero (0.0) 

### LINKED ISSUE #27963: Multiplying a vector by float zero raises an error.
```
from sympy.vector import CoordSys3D
N = CoordSys3D('N')

N.i*0   # This works fine
N.i*0.0 # This raises: AttributeError: 'Zero' object has no attribute '_base_instance'
```
This bug has been present since release 1.13.0 and is still present in 1.14.0rc1. The above code works fine in SymPy 1.12.1.

### PR DESCRIPTION
**Pull request by krishnavbajoria02**
#### References to other Issues or PRs

Fixes #27963

#### Brief description of what is fixed or changed
Previously, multiplying a basis vector (e.g., N.i) by ```0.0``` would raise an ```AttributeError``` due to improper zero detection in the vector module. This commit updates the zero-check logic in ```BasisDependent._new()``` to recognize both ```S.Zero``` and ```0.0``` as zero scalars, restoring expected behavior.

#### Release Notes

NO ENTRY

### CODE REVIEW

**Comment by oscarbenjamin** [comment]
Looks like the test failure might be a hypothesis bug:
```
/opt/hostedtoolcache/Python/3.13.3/x64/lib/python3.13/ast.py:438: in generic_visit
    self.visit(value)
/opt/hostedtoolcache/Python/3.13.3/x64/lib/python3.13/ast.py:428: in visit
    return visitor(node)
/opt/hostedtoolcache/Python/3.13.3/x64/lib/python3.13/ast.py:438: in generic_visit
    self.visit(value)
/opt/hostedtoolcache/Python/3.13.3/x64/lib/python3.13/ast.py:428: in visit
    return visitor(node)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <hypothesis.internal.constants_ast.ConstantVisitor object at 0x7f70d20e8af0>
node = <ast.BinOp object at 0x7f70d2585d90>

    def generic_visit(self, node):
        """Called if no explicit visitor function exists for a node."""
>       for field, value in iter_fields(node):
E       RecursionError: maximum recursion depth exceeded

/opt/hostedtoolcache/Python/3.13.3/x64/lib/python3.13/ast.py:432: RecursionError
```
