### ISSUE TITLE
importing sympy gives error in current master

### ISSUE THREAD

**Issue by ThePauliPrinciple** [sympy/sympy#23153]
https://github.com/sympy/sympy/pull/22677 seems to have caused this @smichr 

on current master locally:
```python
>>> import sympy
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/mnt/c/Users/paul/Documents/PythonScripts/Libs/SymPy/sympy/sympy/__init__.py", line 151, in <module>
    from .concrete import product, Product, summation, Sum
  File "/mnt/c/Users/paul/Documents/PythonScripts/Libs/SymPy/sympy/sympy/concrete/__init__.py", line 1, in <module>
    from .products import product, Product
  File "/mnt/c/Users/paul/Documents/PythonScripts/Libs/SymPy/sympy/sympy/concrete/products.py", line 4, in <module>
    from .summations import Sum, summation, _dummy_with_inherited_properties_concrete
  File "/mnt/c/Users/paul/Documents/PythonScripts/Libs/SymPy/sympy/sympy/concrete/summations.py", line 31, in <module>
    from sympy.polys.polyutils import illegal
ImportError: cannot import name 'illegal' from 'sympy.polys.polyutils' (/mnt/c/Users/paul/Documents/PythonScripts/Libs/SymPy/sympy/sympy/polys/polyutils.py)
```
It fails the code quality check in the CI too.

**Comment by ThePauliPrinciple** [comment]
https://github.com/sympy/sympy/runs/5303557709?check_suite_focus=true

**Comment by jksuom** [comment]
`illegal`was moved to `sympy.core.numbers` and renamed `_illegal`.

**Comment by smichr** [comment]
I can't create the fix now. If someone else can, that would be appreciated.

**Comment by ThePauliPrinciple** [comment]
Maybe we can just revert the offending commit for now?
