### PR TITLE
Fix tuple dyadic pretty printing

### PR DESCRIPTION
**Pull request by vedant3642**
#### References to other Issues or PRs
Fixes #28989 

#### Brief description of what is fixed or changed
This PR fixes a regression in dyadic pretty printing where printing tuples of dyadics raised
`AttributeError: 'Fake' object has no attribute 'height'`.

The regression was introduced after commit 8935af2 (gh-25753), which removed the `Fake` class
from vector pretty printing but left dyadics still using it.
Dyadic pretty printing has now been updated to return proper `prettyForm` objects, following
the same approach used for vectors.

#### AI Generation Disclosure

Some AI assistance was taken initially for test cases in `test_printing.py`, then modified manually as they were not meeting the test criteria and added exact String comparisons manually. Also used in error solving part while writing `_pretty` function.

#### Release Notes

* physics.vector
  * Fixed a regression where printing tuples of dyadics could raise an `AttributeError` under
    `init_printing()`.

### CODE REVIEW

**Comment by moorepants** [comment]
I think this PR is likely completely generated by AI. There is little that resembles how a new contributor would approach this. Please read our AI policy, particularly the part about new contributors. https://docs.sympy.org/dev/contributing/ai-generated-code-policy.html Thus, I am closing this PR.

**Comment by vedant3642** [comment]
> I think this PR is likely completely generated by AI. There is little that resembles how a new contributor would approach this. Please read our AI policy, particularly the part about new contributors. https://docs.sympy.org/dev/contributing/ai-generated-code-policy.html Thus, I am closing this PR.

I did used AI in the `test_printing.py` for generating test cases which later on were changed based on your comments to add exact string comparison.
But during writing `_pretty` function in `dyadic.py` I referred `vector.py` and tried to follow to overcome the Fake class problem in the similar way.

Points I referred from `vector.py` :
-> `for M, N in self.args:` Iterates through the internal coefficient/basis representation
-> `elif M[i] == 1:` and `elif M[i] == -1`  Handles special coefficient cases like 1 and -1
-> `pa = printer._print(a)`  Delegates printing of inner objects using printer._print
-> `pretty_result = prettyForm.__add__(*terms)`  Builds the final result using proper prettyForm objects instead of raw strings

The logic and the use of the above points were done by me to mirror the logic of  `vector.py` . I did use AI to solve errors arose during implementation, queries and doubts purposes but the entire code was not written by AI. Apologies if I didn't mentioned it earlier.
